/* tslint:disable */
export const STUB_CALCULATION = {
  "id": 0,
  "data": {
    "messages": {
      "link": {
        "text": "Get it now from €43.84 /mo",
        "effective_rate": "Eff.rate 9.90%, €2,399.95 per 72 mo, total €3,156.48"
      },
      "bubble": "Hi! Would you prefer to pay €43.84",
      "button": {
        "text": "Get it now from €43.84 /mo",
        "effective_rate": "Eff.rate 9.90%, €2,399.95 per 72 mo, total €3,156.48"
      },
      "banner_and_rate": {
        "month_rate": "€43.84",
        "duration": "72 Months",
        "pay_in": "Pay in 72&nbsp;Months",
        "deferral_charge": "Deferral Charge <br> €43.84",
        "summary": "Eff.rate 9.90%, €2,399.95<br>per 72 mo, total €3,156.48",
        "legal": "Test Legal"
      },
      "banner_and_rate_split": [
        {
          "month_rate": "€411.12",
          "duration": "6 Months",
          "pay_in": "Pay in 6&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €411.12",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 6 mo, total €2,466.72",
          "total": "Total €2,466.72",
          "monthly_amount": null,
          "legal": "Test Legal text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€277.30",
          "duration": "9 Months",
          "pay_in": "Pay in 9&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €277.30",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 9 mo, total €2,495.70",
          "total": "Total €2,495.70",
          "monthly_amount": null,
          "legal": "Test Legal text 2",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€250.54",
          "duration": "10 Months",
          "pay_in": "Pay in 10&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €250.54",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 10 mo, total €2,505.40",
          "total": "Total €2,505.40",
          "monthly_amount": null,
          "legal": "Test Legal text 3",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€210.41",
          "duration": "12 Months",
          "pay_in": "Pay in 12&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €210.41",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 12 mo, total €2,524.92",
          "total": "Total €2,524.92",
          "monthly_amount": null,
          "legal": "Test Legal text 4",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€143.56",
          "duration": "18 Months",
          "pay_in": "Pay in 18&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €143.56",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 18 mo, total €2,584.08",
          "total": "Total €2,584.08",
          "monthly_amount": null,
          "legal": "Test Legal text 5",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€130.20",
          "duration": "20 Months",
          "pay_in": "Pay in 20&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €130.20",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 20 mo, total €2,604.00",
          "total": "Total €2,604.00",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€110.18",
          "duration": "24 Months",
          "pay_in": "Pay in 24&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €110.18",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 24 mo, total €2,644.32",
          "total": "Total €2,644.32",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€90.17",
          "duration": "30 Months",
          "pay_in": "Pay in 30&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €90.17",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 30 mo, total €2,705.10",
          "total": "Total €2,705.10",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€76.87",
          "duration": "36 Months",
          "pay_in": "Pay in 36&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €76.87",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 36 mo, total €2,767.32",
          "total": "Total €2,767.32",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€67.37",
          "duration": "42 Months",
          "pay_in": "Pay in 42&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €67.37",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 42 mo, total €2,829.54",
          "total": "Total €2,829.54",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€60.30",
          "duration": "48 Months",
          "pay_in": "Pay in 48&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €60.30",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 48 mo, total €2,894.40",
          "total": "Total €2,894.40",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€54.79",
          "duration": "54 Months",
          "pay_in": "Pay in 54&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €54.79",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 54 mo, total €2,958.66",
          "total": "Total €2,958.66",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€50.37",
          "duration": "60 Months",
          "pay_in": "Pay in 60&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €50.37",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 60 mo, total €3,022.20",
          "total": "Total €3,022.20",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€46.84",
          "duration": "66 Months",
          "pay_in": "Pay in 66&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €46.84",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 66 mo, total €3,091.44",
          "total": "Total €3,091.44",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        },
        {
          "month_rate": "€43.84",
          "duration": "72 Months",
          "pay_in": "Pay in 72&nbsp;Months",
          "deferral_charge": "Deferral Charge <br> €43.84",
          "summary": "Eff.rate 9.90%, €2,399.95<br>per 72 mo, total €3,156.48",
          "total": "Total €3,156.48",
          "monthly_amount": null,
          "legal": "Test Legal Text",
          "effective_rate": "Test effective rate"
        }
      ]
    },
    "credit": [
      {
        "bank_interest": 66.77,
        "cpi_amount": 0,
        "duration": 6,
        "interest_rate": 9.9,
        "monthly_rate": 411.12,
        "price": 2399.95,
        "rate_pa": 8.5,
        "total_amount": 2466.72,
        "first_instalment": 411.12,
        "loan_amount": 2399.95,
        "loan_fee": 66.77,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 95.75,
        "cpi_amount": 0,
        "duration": 9,
        "interest_rate": 9.9,
        "monthly_rate": 277.3,
        "price": 2399.95,
        "rate_pa": 8.768,
        "total_amount": 2495.7,
        "first_instalment": 277.3,
        "loan_amount": 2399.95,
        "loan_fee": 95.75,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 105.45,
        "cpi_amount": 0,
        "duration": 10,
        "interest_rate": 9.9,
        "monthly_rate": 250.54,
        "price": 2399.95,
        "rate_pa": 8.826,
        "total_amount": 2505.4,
        "first_instalment": 250.54,
        "loan_amount": 2399.95,
        "loan_fee": 105.45,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 124.97,
        "cpi_amount": 0,
        "duration": 12,
        "interest_rate": 9.9,
        "monthly_rate": 210.41,
        "price": 2399.95,
        "rate_pa": 8.921,
        "total_amount": 2524.92,
        "first_instalment": 210.41,
        "loan_amount": 2399.95,
        "loan_fee": 124.97,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 184.13,
        "cpi_amount": 0,
        "duration": 18,
        "interest_rate": 9.9,
        "monthly_rate": 143.56,
        "price": 2399.95,
        "rate_pa": 9.089,
        "total_amount": 2584.08,
        "first_instalment": 143.56,
        "loan_amount": 2399.95,
        "loan_fee": 184.13,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 204.05,
        "cpi_amount": 0,
        "duration": 20,
        "interest_rate": 9.9,
        "monthly_rate": 130.2,
        "price": 2399.95,
        "rate_pa": 9.125,
        "total_amount": 2604,
        "first_instalment": 130.2,
        "loan_amount": 2399.95,
        "loan_fee": 204.05,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 244.37,
        "cpi_amount": 0,
        "duration": 24,
        "interest_rate": 9.9,
        "monthly_rate": 110.18,
        "price": 2399.95,
        "rate_pa": 9.186,
        "total_amount": 2644.32,
        "first_instalment": 110.18,
        "loan_amount": 2399.95,
        "loan_fee": 244.37,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 305.15,
        "cpi_amount": 0,
        "duration": 30,
        "interest_rate": 9.9,
        "monthly_rate": 90.17,
        "price": 2399.95,
        "rate_pa": 9.236,
        "total_amount": 2705.1,
        "first_instalment": 90.17,
        "loan_amount": 2399.95,
        "loan_fee": 305.15,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 367.37,
        "cpi_amount": 0,
        "duration": 36,
        "interest_rate": 9.9,
        "monthly_rate": 76.87,
        "price": 2399.95,
        "rate_pa": 9.283,
        "total_amount": 2767.32,
        "first_instalment": 76.87,
        "loan_amount": 2399.95,
        "loan_fee": 367.37,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 429.59,
        "cpi_amount": 0,
        "duration": 42,
        "interest_rate": 9.9,
        "monthly_rate": 67.37,
        "price": 2399.95,
        "rate_pa": 9.299,
        "total_amount": 2829.54,
        "first_instalment": 67.37,
        "loan_amount": 2399.95,
        "loan_fee": 429.59,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 494.45,
        "cpi_amount": 0,
        "duration": 48,
        "interest_rate": 9.9,
        "monthly_rate": 60.3,
        "price": 2399.95,
        "rate_pa": 9.343,
        "total_amount": 2894.4,
        "first_instalment": 60.3,
        "loan_amount": 2399.95,
        "loan_fee": 494.45,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 558.71,
        "cpi_amount": 0,
        "duration": 54,
        "interest_rate": 9.9,
        "monthly_rate": 54.79,
        "price": 2399.95,
        "rate_pa": 9.353,
        "total_amount": 2958.66,
        "first_instalment": 54.79,
        "loan_amount": 2399.95,
        "loan_fee": 558.71,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 622.25,
        "cpi_amount": 0,
        "duration": 60,
        "interest_rate": 9.9,
        "monthly_rate": 50.37,
        "price": 2399.95,
        "rate_pa": 9.339,
        "total_amount": 3022.2,
        "first_instalment": 50.37,
        "loan_amount": 2399.95,
        "loan_fee": 622.25,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 691.49,
        "cpi_amount": 0,
        "duration": 66,
        "interest_rate": 9.9,
        "monthly_rate": 46.84,
        "price": 2399.95,
        "rate_pa": 9.389,
        "total_amount": 3091.44,
        "first_instalment": 46.84,
        "loan_amount": 2399.95,
        "loan_fee": 691.49,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      },
      {
        "bank_interest": 756.53,
        "cpi_amount": 0,
        "duration": 72,
        "interest_rate": 9.9,
        "monthly_rate": 43.84,
        "price": 2399.95,
        "rate_pa": 9.372,
        "total_amount": 3156.48,
        "first_instalment": 43.84,
        "loan_amount": 2399.95,
        "loan_fee": 756.53,
        "processing_fee": 0,
        "initial_min_rate": 0,
        "interest_free_duration": 0,
        "is_wish_calculation": false
      }
    ]
  }
}
