{{ $chartName := .Chart.Name }}
{{ $values := .Values }}
{{ $appName := $chartName }}

apiVersion: v1
kind: Service

metadata:
  name: {{ $appName }}
  namespace: {{ $values.namespace }}

  labels:
    app: {{ $appName}}

spec:
  type: ClusterIP

  selector:
    app: {{ $appName }}

  ports:
    - protocol: TCP
      port: {{ $values.service.externalPort }}
      targetPort: {{ $values.service.containerPort }}
      name: http
