namespace: default
priorityClass: app-10stars
domain: 'test.devpayever.com'
issue: ''
microCheckoutVersion: 1.0.0
microUrlCommerceosVersion: 1.0.0
replicas:
  http: 6

image:
  nginx: registry.devpayever.com/frontend/connect
  pullSecretName: regsecret

service:
  tlsSecretName: tls-wild-test-devpayever-com
  externalPort: 80
  containerPort: 80
  monitoringPort: 8080

resources:
  requests:
    cpu: 250m
    memory: 132Mi
  limits:
    memory: 2Gi
