import { AddressTypeEnum, FlowInterface, FlowStateEnum, PaymentMethodEnum } from '@pe/checkout/types';
import { cloneDeep } from '@pe/checkout/utils';

export const flowWithPaymentOptionsFixture: () => FlowInterface = () => cloneDeep<FlowInterface>({
  id: '4abed55c98e9a07466ed1396f521e6d3',
  amount: 1000,
  total: 0,
  taxValue: 0,
  currency: 'EUR',
  shippingAddressId: null,
  billingAddress: {
    fullAddress: '',
    id: '4095f542-ae0d-4fff-9314-ae1f51381e3b',
    salutation: null,
    firstName: null,
    lastName: null,
    phone: null,
    country: null,
    countryName: '',
    city: null,
    zipCode: null,
    street: null,
    streetName: null,
    streetNumber: null,
    organizationName: null,
    email: null,
    type: AddressTypeEnum.BILLING,
    socialSecurityNumber: null,
  },
  businessShippingOptionId: null,
  shippingMethodCode: '',
  shippingMethodName: '',
  shippingCategory: null,
  connectionId: 'insb5f52-7859-4ba0-a20f-d271200be4db',
  channel: 'link',
  channelSetId: '1d802abf-13da-47a4-8b46-02366250c6a9',
  cart: [],
  paymentOptions: [
    {
      connections: [
        {
          id: 'insb5f52-7859-4ba0-a20f-d271200be4db',
          merchantCoversFee: false,
          shippingAddressAllowed: false,
          shippingAddressEquality: false,
        },
      ],
      name: 'Paypal',
      slug: 'Paypal',
      settings: null,
      min: 0,
      max: 100000,
      fixedFee: 0,
      variableFee: 0,
      acceptFee: true,
      paymentMethod: PaymentMethodEnum.PAYPAL,
    },
  ],
  shippingAddresses: [],
  state: FlowStateEnum.PROGRESS,
  shopUrl: null,
  apiCall: {
    id: '1234',
    phone_number: null,
    salutation: null,
    firstName: null,
    lastName: null,
    birthDate: null,
    zipCode: null,
    ssn: null,
    failureUrl: null,
    successUrl: null,
    customerRedirectUrl: null,
    cancelUrl: 'https://webhook.site/59847d5c-e0e5-4da0-985e-ed7d2e72a764',
    pendingUrl: null,
    x_frame_host: null,
  },
  payment: null,
  singleAddress: true,
  reference: null,
  flashBag: null,
  express: false,
  userAccountId: null,
  financeType: null,
  hideSalutation: false,
  successUrl: 'https://we123bhook.site/59847d5c-e0e5-4da0-985e-ed7d2e72a764123',
  failureUrl: 'https://webhook.site/59847d5c-e0e5-4da0-985e-ed7d2e72a764',
  cancelUrl: 'https://webhook.site/59847d5c-e0e5-4da0-985e-ed7d2e72a764',
  pendingUrl: 'https://webhook.site/59847d5c-e0e5-4da0-985e-ed7d2e72a764',
  noticeUrl: 'https://webhook.site/59847d5c-e0e5-4da0-985e-ed7d2e72a764',
  deliveryFee: null,
  comment: null,
  values: [],
  businessId: '',
  businessName: '',
  businessIban: '',
  businessAddressLine: 'Hamilton, 48111, Hamburg, Germany',
  pos_merchant_mode: null,
  posVerifyType: null,
  shippingOrderId: null,
  extra: {
    posVerifyType: 0,
  },
  shopUserSession: null,
  coupon: null,
});
