import * as THREE from "three";

export const THREEJS_DEFAULTS = {
  defaultWidth: 900,
  defaultHeight: 600,
  defaultCameraPosition: new THREE.Vector3(0, 0, 10),
  defaultAmbientLightIntensity: 0.3,
  defaultAmbientLightColor: 0xffffff,
  defaultDirectionalLightIntensity: 0.8 * Math.PI,
  defaultDirectionalLightColor: 0xffffff,
  defaultDirectionalLightPosition: new THREE.Vector3(0, 1, 0),
  defaultCameraFOV: 60,
  defaultCameraNearPlane: 0.1,
  defaultCameraFarPlane: 1000,
  defaultControlDampingFactor: 0.05,
  defaultControlMinPolarAngle: Math.PI / 4,
  defaultControlMaxPolarAngle: Math.PI / 2,
  defaultControlZoomSpeed: 1.0,
  defaultControlsDamping: true,
  defaultControlsDampingFactor: 0.05,
  defaultMinPolarAngle: 0,
  defaultMaxPolarAngle: Math.PI / 2,
  defaultMinAzimuthAngle: 0,
  defaultMaxAzimuthAngle: Math.PI / 4,
  defaultZoomSpeed: 1.0,
  defaultTuneMapping: THREE.ACESFilmicToneMapping,
  defaultTuneMappingExposure: 1.0,
  defaultCameraDistanceRatio : 0.85,
  defaultEnableZoom: false,
};
