import {
  PebDocumentElement,
  PebDocumentMakerElement,
  PebGridCellCategoryElement,
  PebGridCellCategoryMakerElement,
  PebGridCellElement,
  PebGridCellFilterSelectElement,
  PebGridCellFilterSelectMakerElement,
  PebGridCellMakerElement,
  PebGridCellProductElement,
  PebGridCellProductMakerElement,
  PebGridCellSortSelectElement,
  PebGridCellSortSelectMakerElement,
  PebGridElement,
  PebGridMakerElement,
  PebGroupElement,
  PebGroupMakerElement,
  PebSectionElement,
  PebSectionMakerElement,
  PebShapeElement,
  PebShapeMakerElement,
  PebTextElement,
  PebTextMakerElement,
} from '@pe/builder-base-plugins';

export const pebInvoiceElementsConfig = {
  elements: {
    lazy: {
      button: () => import('@pe/builder-base-plugins/elements/button/client').then(m => m.PebButtonElement),
      carousel: () => import('@pe/builder-base-plugins/elements/carousel/client').then(m => m.PebCarouselElement),
      html: () => import('@pe/builder-base-plugins/elements/html/client').then(m => m.PebHtmlElement),
      image: () => import('@pe/builder-base-plugins/elements/image/client').then(m => m.PebImageElement),
      line: () => import('@pe/builder-base-plugins/elements/line/client').then(m => m.PebLineElement),
      logo: () => import('@pe/builder-base-plugins/elements/logo/client').then(m => m.PebLogoElement),
      menu: () => import('@pe/builder-base-plugins/elements/menu/client').then(m => m.PebMenuElement),
      script: () => import('@pe/builder-base-plugins/elements/script/client').then(m => m.PebScriptElement),
      'social-icon': () => import('@pe/builder-base-plugins/elements/social-icon/client').then(m => m.PebSocialIconElement),
      video: () => import('@pe/builder-base-plugins/elements/video/client').then(m => m.PebVideoElement),

      'shop-cart': () => import(`@pe/builder-shop-plugins/elements/cart/client`).then(m => m.PebShopCartElement),
      'shop-category': () => import('@pe/builder-shop-plugins/elements/category/client').then(m => m.PebShopCategoryElement),
      'shop-product-details': () => import('@pe/builder-shop-plugins/elements/product-details/client').then(m => m.PebShopProductDetailsElement),
      'shop-products': () => import('@pe/builder-shop-plugins/elements/product-grid/client').then(m => m.PebShopProductsElement),
      'pos-catalog': () => import('@pe/builder-shop-plugins/elements/catalog/client').then(m => m.PebPosCatalogElement),
      languages: () => import('@pe/builder-shop-plugins/elements/languages/client').then(m => m.PebShopLanguagesElement),
    },
    preloaded: {
      document: PebDocumentMakerElement,
      grid: PebGridMakerElement,
      'grid-cell': PebGridCellMakerElement,
      'grid-cell-product': PebGridCellProductMakerElement,
      'grid-cell-category': PebGridCellCategoryMakerElement,
      'grid-cell-filter-select': PebGridCellFilterSelectMakerElement,
      'grid-cell-sort-select': PebGridCellSortSelectMakerElement,
      group: PebGroupMakerElement,
      section: PebSectionMakerElement,
      shape: PebShapeMakerElement,
      text: PebTextMakerElement,
    },
    client: {
      document: PebDocumentElement,
      grid: PebGridElement,
      'grid-cell': PebGridCellElement,
      'grid-cell-product': PebGridCellProductElement,
      'grid-cell-category': PebGridCellCategoryElement,
      'grid-cell-filter-select': PebGridCellFilterSelectElement,
      'grid-cell-sort-select': PebGridCellSortSelectElement,
      group: PebGroupElement,
      section: PebSectionElement,
      shape: PebShapeElement,
      text: PebTextElement,
    },
  },
};
