import { AddressTypeEnum, CustomWidgetConfigInterface } from '@pe/checkout/types';
import { cloneDeep } from '@pe/checkout/utils';

export const widgetConfigFixture: () => CustomWidgetConfigInterface = () => cloneDeep<CustomWidgetConfigInterface>({
  business: 'config-business',
  businessId: 'config-businessId',
  widgetId: 'config-widgetId',
  amount: 100.50,
  reference: 'config-reference',
  isDebugMode: false,
  shippingOption: {
    name: 'config-shippingOption-name',
    price: 105.50,
  },
  minWidth: 300,
  maxWidth: 500,
  minHeight: 200,
  maxHeight: 300,
  shippingOptions: [],
  billingAddress: {
    organizationName: 'payever-billing',
    email: 'payever-test@payever.org',
    fullAddress: '123 Main st, Berlin, DE',
    id: 'billing-address-id',
    type: AddressTypeEnum.BILLING,
    region: 'DE',
  },
  shippingAddress: {
    organizationName: 'payever-shipping',
    email: 'payever-test@payever.org',
    fullAddress: '123 Main st, Berlin, DE',
    id: 'billing-address-id',
    type: AddressTypeEnum.SHIPPING,
    region: 'DE',
  },
  theme: 'light',
  alignment: 'left',
  quoteCallbackUrl: 'https://config-quote-callback-url.com',
  successUrl: 'https://config-payever-success-url.com',
  cancelUrl: 'https://config-payever-cancel-url.com',
  failureUrl: 'https://config-payever-failure-url.com',
  cart: [
    {
      description: 'Item description',
      identifier: 'item-1',
      price: 25.25,
      quantity: 2,
      thumbnail: 'https://payever.org/item-thumbnail-1.jpg',
      name: 'Item 1',
      unit: 'pcs',
      amount: 50.50,
    },
    {
      description: 'Item description',
      identifier: 'item-2',
      price: 15.75,
      quantity: 3,
      thumbnail: 'https://payever.org/item-thumbnail-2.jpg',
      name: 'Item 2',
      unit: 'pcs',
      amount: 47.25,
    },
  ],
});
