import { PaymentMethodEnum } from '@pe/checkout/types';

import { PaymentSummaryConfig } from '../models';

import {
  SANTANDER_DE_FACT_VARIANT_CONFIG,
  SANTANDER_DE_POS_VARIANT_CONFIG,
  SANTANDER_DE_VARIANT_CONFIG,
  SANTANDER_DK_VARIANT_CONFIG,
  SANTANDER_NO_VARIANT_CONFIG,
  SANTANDER_SE_VARIANT_CONFIG,
} from './variants';

type PaymentSummaryConfigMap = {
  [Key in PaymentMethodEnum]?: PaymentSummaryConfig;
}

export const PAYMENT_SUMMARY_CONFIG_MAP: PaymentSummaryConfigMap = {
  [PaymentMethodEnum.SANTANDER_FACTORING_DE]: SANTANDER_DE_FACT_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_POS_FACTORING_DE]: SANTANDER_DE_FACT_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_INSTALLMENT]: SANTANDER_DE_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_POS_INSTALLMENT]: SANTANDER_DE_POS_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_INSTALLMENT_DK]: SANTANDER_DK_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_POS_INSTALLMENT_DK]: SANTANDER_DK_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_INSTALLMENT_NO]: SANTANDER_NO_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_POS_INSTALLMENT_NO]: SANTANDER_NO_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_INSTALLMENT_SE]: SANTANDER_SE_VARIANT_CONFIG,
  [PaymentMethodEnum.SANTANDER_POS_INSTALLMENT_SE]: SANTANDER_SE_VARIANT_CONFIG,
};
