{{- $chartName := .Chart.Name }}
{{- $values := .Values }}
{{- $appName := printf "%s-%s" $chartName $values.issue | lower | replace "_" "-" | trimSuffix "-"  }}
{{- $serviceName := printf "%s-%s" $chartName $values.issue | lower | replace "_" "-" | trimSuffix "-"  }}

{{- if .Values.deployToExclusive -}}
  {{- if $values.mainDeploy }}
    {{- $serviceName = regexReplaceAll "-wrapper$" $serviceName "" }}
  {{- end }}

apiVersion: v1
kind: Service

metadata:
  name: {{ $serviceName }}
  namespace: {{ $values.namespace }}

  labels:
    app: {{ $appName}}

spec:
  type: ClusterIP

  selector:
    app: {{ $appName }}

  ports:
    - protocol: TCP
      port: {{ $values.service.externalPort }}
      targetPort: {{ $values.service.containerPort }}
      name: http
{{- end -}}
