namespace: default
priorityClass: app-10stars
domain: 'test.devpayever.com'
issue: ''
deployToExclusive: true
replicas:
  http: 1

image:
  nginx: registry.devpayever.com/frontend/assets
  pullSecretName: regsecret

service:
  tlsSecretName: tls-test-devpayever-com
  externalPort: 80
  containerPort: 80
  monitoringPort: 8080

serviceBuilderClient:
  externalPort: 80
  containerPort: 3000
  statusPort: 3000

#Resources
test:
  resources:
    requests:
      cpu: 50m
      memory: 250Mi
    limits:
      memory: 464Mi
stage:
  resources:
    requests:
      cpu: 50m
      memory: 250Mi
    limits:
      memory: 464Mi
live:
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      memory: 464Mi
job:
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      memory: 1Gi
istio:
  proxyMemoryLimit: 300Mi
