{{ $chartName := .Chart.Name }}
{{ $values := .Values }}
{{ $appName := $chartName }}
{{ $nginxConfigName:= printf "%s-nginx" $appName }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $nginxConfigName }}
  namespace: {{ $values.namespace }}

  labels:
    app: {{ $nginxConfigName }}

data:
  default.conf: |
    server {
        listen   80;
        listen   8080;
        root /payever/dist/client;

        gzip on;
        gzip_types text/plain text/css application/json  application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript font/woff2 application/font-woff2 ;

        location / {
            try_files $uri $uri @backend;
        }

        location /api/status {
            add_header Content-Type text/plain;
            access_log  off;
        }

        location @backend {
            proxy_pass http://127.0.0.1:4100;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        location ~* \.(?:cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|css|js|woff2|woff|png|jpeg|jpg)$ {
          expires 30d;
          access_log off;
          add_header Cache-Control "public";
        }

        location ~ /(deploy.sh|post-deploy.sh) {
            return 404;
        }
    }
