import { AlphaChannel, OutputFormat } from "./helpers";

export interface DialogStyles {
  color: any,
  cpWidth: string,
  cpHeight: string,
  cpDialogDisplay: string,
  cpFallbackColor: string,
  cpColorMode: string,
  cpCmykEnabled: boolean,
  cpAlphaChannel: AlphaChannel,
  cpOutputFormat: OutputFormat,
  cpDisableInput: boolean,
  cpIgnoredElements: any,
  cpSaveClickOutside: boolean,
  cpCloseClickOutside: boolean,
  cpUseRootViewContainer: boolean,
  cpPosition: string,
  cpPositionOffset: string,
  cpPositionRelativeToArrow: boolean,
  cpPresetLabel: string,
  cpPresetColors: string[],
  cpPresetColorsClass: string,
  cpMaxPresetColorsLength: number,
  cpPresetEmptyMessage: string,
  cpPresetEmptyMessageClass: string,
  cpOKButton: boolean,
  cpOKButtonClass: string,
  cpOKButtonText: string,
  cpCancelButton: boolean,
  cpCancelButtonClass: string,
  cpCancelButtonText: string,
  cpAddColorButton: boolean,
  cpAddColorButtonClass: string,
  cpAddColorButtonText: string,
  cpRemoveColorButtonClass: string
}
