export enum PaymentDemo {
  ZINIA = 'Zinia',
  ALLIANZ = 'Allianz',
  INSTANT = 'Instant',
  SWEDBANK_INVOICE = 'SwedbankInvoice',
  SWEDBANK_CREDIT_CARD = 'SwedbankCreditCard',
  IDEAL = 'Ideal',
  IVY = 'IVY',
  VIPPS = 'Vipps',
  PAYPAL = 'PayPal',
  SWISH = 'Swish',
  SANTANDER_INSTALLMENT_DE = 'SantanderInstallmentDE',
  SANTANDER_INSTALLMENT_AT = 'SantanderInstallmentAT',
  SANTANDER_INSTALLMENT_UK = 'SantanderInstallmentUK',
  SANTANDER_INSTALLMENT_DE_POS = 'SantanderInstallmentDEPoS',
  SANTANDER_INSTALLMENT_SE = 'SantanderInstallmentSE',
  SANTANDER_INSTALLMENT_NO = 'SantanderInstallmentNO',
  SANTANDER_INSTALLMENT_DK = 'SantanderInstallmentDK',
  SANTANDER_INSTALLMENT_FI = 'SantanderInstallmentFI',
  SANTANDER_INSTALLMENT_NL = 'SantanderInstallmentNL',
  SANTANDER_INSTALLMENT_BE = 'SantanderInstallmentBE',
  MOBILE_PAY = 'MobilePay',
  TRUSTLY = 'Trustly',
  STRIPE_DEBIT_CARD = 'StripeDebitCard',
  STRIPE_CREDIT_CARD = 'StripeCreditCard',
  SOFORT = 'Sofort',
  GOOGLE_PAY = 'GooglePay',
  APPLE_PAY = 'ApplePay',
  WIRE_TRANSFER = 'WireTransfer',
};

export enum Currency {
  KRONA = "kr",
  EURO = "euro",
};