// TODO: HARDCODED MOCKS!
export const channels: any = [
  {
    "name":"E-Conomic",
    "description":"\u003Cp\u003EOur e-conomic app enables you to accept PayPal &amp; Credit Card payments directly in your e-conomic invoice. For free.\u003C\/p\u003E\r\n\r\n\u003Cp\u003EChoose the payment options you want to offer, connect your e-conomic account and customize the invoice mail you are going to send to your customers. Finally, copy the HTML code and paste it into your e-conomic account. Your customer will see a payment button which they can use to simply pay the invoice online.&nbsp;\u003C\/p\u003E",
    "type":"e-conomic",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/e-conomic.png"
  }
  ,
  {
    "name":"Debitoor",
    "description":"\u003Cp\u003EAccept payments via PayPal, Credit Card, Direct Debt &amp; Sofort\u00fcberweisung directly in your Debitoor invoices. Full integration with your accounting.\u003C\/p\u003E\n\n\u003Cp\u003EChoose the payment options you want to offer, connect your Debitoor account, and you can start. Your customer will see a payment button which he can use to instantly pay the invoice online.&nbsp;\u003C\/p\u003E",
    "type":"debitoor",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/debitoor.png"
  }
  ,
  {
    "name":"Facebook",
    "description":"\u003Cp\u003ESearching for a new selling channel? How about 1 billion potential customers? Start selling on facebook in minutes.\u003C\/p\u003E",
    "type":"facebook",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/facebook.png"
  }
  ,
  {
    "name":"Store",
    "description":"\u003Cp\u003ECreate your personal store in minutes and start selling directly on your website or via shared link.\u003C\/p\u003E",
    "type":"store",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/store.png"
  }
  ,
  {
    "name":"Link",
    "description":"\u003Cp\u003E\u003C\/p\u003E",
    "type":"link",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/other_shopsystem.png"
  }
  ,
  {
    "name":"Shopware",
    "description":"\u003Cp\u003EInstall our Shopware plugin and accept all payment options in your&nbsp;online store.\u003C\/p\u003E\r\n\r\n\u003Cp\u003EMore than 200 Shopware stores are using our solution. Add more payment options to your store in minutes:\u003C\/p\u003E\r\n\r\n\u003Cp\u003E1. Add the payment options you need\u003C\/p\u003E\r\n\r\n\u003Cp\u003E2. Configure instructions of the payment options to include on your webpage (optional)\u003C\/p\u003E\r\n\r\n\u003Cp\u003E3. Add&nbsp;more apps,&nbsp;for example, to keep track of your accounting (optional)\u003C\/p\u003E\r\n\r\n\u003Cp\u003E4. Activate Finance Express&nbsp;(optional)\u003C\/p\u003E\r\n\r\n\u003Cp\u003E5. Download the plugin and the instructions either here or directly at the Shopware Store\u003C\/p\u003E",
    "type":"shopware",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/shopware.png"
  }
  ,
  {
    "name":"Magento",
    "description":"\u003Cp\u003EInstall our Magento plugin and accept all payment options in your&nbsp;online store.\u003C\/p\u003E\r\n\r\n\u003Cp\u003EAdd more payment options to your store in minutes:\u003C\/p\u003E\r\n\r\n\u003Cp\u003E1. Add the payment options you need\u003C\/p\u003E\r\n\r\n\u003Cp\u003E2. Configure instructions of the payment options to include on your webpage (optional)\u003C\/p\u003E\r\n\r\n\u003Cp\u003E3. Add&nbsp;more apps,&nbsp;for example, to keep track of your accounting (optional)\u003C\/p\u003E\r\n\r\n\u003Cp\u003E4. Download the plugin and the instructions\u003C\/p\u003E",
    "type":"magento",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/magento.png"
  }
  ,
  {
    "name":"payever POS",
    "description":"\u003Cp\u003EDeine neue Kassensystem-App f\u00fcr die Bezahlung vor Ort.\u003C\/p\u003E\r\n\r\n\u003Cp\u003E&nbsp;\u003C\/p\u003E",
    "type":"pos",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/pos.png"
  }
  ,
  {
    "name":"JTL",
    "description":"\u003Cp\u003EActivate (shop system) and set up the channel to accept all payment methods in your online shop.\u003C\/p\u003E",
    "type":"jtl",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/jtl.png"
  }
  ,
  {
    "name":"OXID",
    "description":"\u003Cp\u003EActivate OXID and set up the channel to accept all payment methods in your online shop.\u003C\/p\u003E",
    "type":"oxid",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/oxid.png"
  }
  ,
  {
    "name":"xt:Commerce",
    "description":"\u003Cp\u003EActivate xt:Commerce&nbsp;and set up the channel to accept all payment methods in your online shop.\u003C\/p\u003E",
    "type":"xt_commerce",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/xt_commerce.png"
  }
  ,
  {
    "name":"Weebly",
    "description":"\u003Cp\u003EActivate Weebly and set up the channel to accept all payment methods in your online shop.\u003C\/p\u003E",
    "type":"weebly",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/weebly.png"
  }
  ,
  {
    "name":"WooCommerce",
    "description":"\u003Cp\u003EActivate WooCommerce and set up the channel to accept all payment methods in your online shop.\u003C\/p\u003E\n\n\u003Cp\u003E&nbsp;\u003C\/p\u003E",
    "type":"wooCommerce",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/wooCommerce.png"
  }
  ,
  {
    "name":"PrestaShop",
    "description":"\u003Cp\u003EActivate PrestaShop and set up the channel to accept all payment methods in your online shop.\u003C\/p\u003E",
    "type":"presta",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/presta.png"
  }
  ,
  {
    "name":"Marketing",
    "description":"\u003Cp\u003ESend offers by mail\u003C\/p\u003E\n\n\u003Cp\u003E&nbsp;\u003C\/p\u003E",
    "type":"marketing",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/marketing.png"
  }
  ,
  {
    "name":"Shopify",
    "description":"Integrate payever in minutes and accept all payments in your Shopify store.",
    "type":"shopify",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/shopify.png"
  }
  ,
  {
    "name":"Overlay",
    "description":"Integrate overlay and setup banners for all your shops.",
    "type":"overlay",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/overlay.png"
  }
  ,
  {
    "name":"DanDomain",
    "description":"\u003Cp\u003EIntegrate payever in minutes and accept all payment methods in your online shop.\u003C\/p\u003E",
    "type":"dandomain",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/3794bbdc296906ed5e159cc5ea4c29ec.png"
  }
  ,
  {
    "name":"Offer",
    "description":"\u003Cp\u003E\u003C\/p\u003E",
    "type":"offer",
    "thumbnail":null},
  {
    "name":"Advertising",
    "description":"\u003Cp\u003E\u003C\/p\u003E",
    "type":"advertising",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/resolve\/channels.list\/advertising.png"
  }
  ,
  {
    "name":"Finance Express",
    "description":"\u003Cp\u003E\u003C\/p\u003E",
    "type":"finance_express",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/channels.list\/finance_express.png"
  }
  ,
  {
    "name":"plentymarkets",
    "description":"\u003Cp\u003EActivate plentymarkets and set up the channel to accept all payment methods in your online shop.\u003C\/p\u003E",
    "type":"plentymarkets",
    "thumbnail":"https:\/\/stage.payever.de\/media\/cache\/resolve\/channels.list\/plentymarkets.png"
  }
  ,
  {
    "name":"Api",
    "description":"",
    "type":"api",
    "thumbnail":""
  }
];

export const paymentOptions: any = [{
  "name":"SOFORT Banking",
  "description_offer":"\u003Cp\u003ESimply pay while you are shopping online. By entering your familiar online banking login details and confirmation codes with a maximum level of security. The online shop will receive a real-time transaction confirmation immediately after the transfer has been listed.\u003C\/p\u003E",
  "description_fee":"\u003Cp\u003EOffer SOFORT Banking to your customers. All fees are only transaction based. Starting from 0.8% + 0.15\u20ac per transaction.\u003C\/p\u003E",
  "id":12,"status":"active",
  "variable_fee":0.8,"fixed_fee":0.15,"contract_length":0,"payment_method":"sofort",
  "related_country":null,"merchant_allowed_countries":["DE",
    "BE",
    "FR",
    "IT",
    "NL",
    "AT",
    "PL",
    "CH",
    "SK",
    "ES",
    "CZ",
    "HU",
    "GB"],"slug":"sofort",
  "instruction_text":"Create a new project and make sure that you use a SOFORTGateway-Project and choose \"payever GmbH\" as a Shop System. Enter the SOFORT Configuration-Key in your payever merchant account. Done!",
  "info_url":"https:\/\/getpayever.com\/payment\/sofort\/",
  "thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/2e84275ce75a614d9a78d8da4f063193.png",
  "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/3e81a28027e3c56f8b55d6eb81bc3ace.png",
  "min":0,"max":100000},
  {
    "name":"Invoice",
    "description_offer":"\u003Cp\u003ESimply pay after delivery. You receive your purchase first and then pay within 14 days. You can find all payment information right on your invoice.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EFor only 3.6% + 0.65\u20ac you can offer your customers the most popular payment option.\u003C\/p\u003E",
    "id":13,"status":"disabled",
    "variable_fee":3.6,"fixed_fee":0.65,"contract_length":12,"payment_method":"invoice",
    "related_country":null,"merchant_allowed_countries":["DE"],"slug":"invoice",
    "instruction_text":"Simply enter your PayProtect credentials, or apply for a new account.",
    "info_url":"https:\/\/getpayever.com\/payment\/invoice\/",
    "thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/02aaa6fb7dd1964337d8f7de7e0d41ac.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/invoice_2.png",
    "min":5,"max":250},
  {
    "name":"Wire Transfer",
    "description_offer":"\u003Cp\u003EShop, send money directly to the merchant, and receive your goods. Simple as that.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EYou always have the option to enable&nbsp;Wire Transfer directly in your payever shops.&nbsp;\u003C\/p\u003E",
    "id":15,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"cash",
    "related_country":null,"merchant_allowed_countries":["DE",
      "FR",
      "LI",
      "LU",
      "NL",
      "AT",
      "PT",
      "CH",
      "ES",
      "GB"],"slug":"cash",
    "instruction_text":"Complete your \naccount information accurately, so that your customers know where to send payments.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/06066a7119fa78a0679b05082cdebaf2.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/63116ba115f4e767d8bfb42c9ac4b3d7.png",
    "min":0,"max":100000},
  {
    "name":"Paymill Credit Card",
    "description_offer":"\u003Cp\u003EPayment by credit card. We accept MasterCard and Visa.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAkzeptieren Sie Kreditkartenzahlungen ohne PCI-Zertifizierung!\u003C\/p\u003E",
    "id":17,"status":"active",
    "variable_fee":2.95,"fixed_fee":0.28,"contract_length":0,"payment_method":"paymill_creditcard",
    "related_country":null,"merchant_allowed_countries":["DE"],"slug":"paymill",
    "instruction_text":"Simply enter the keys from your Paymill account, or  create a new Paymill account.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/aeec8bef1c8681ee4ac1960066d49b43.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/412a586290b5d728615a9e69d753f7ea.png",
    "min":0,"max":10000},
  {
    "name":"Direct Debit",
    "description_offer":"\u003Cp\u003EEasily pay with direct debit.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EOffer direct debit to your customers for only 0.28\u20ac per transaction.\u003C\/p\u003E",
    "id":25,"status":"active",
    "variable_fee":0,"fixed_fee":0.28,"contract_length":0,"payment_method":"paymill_directdebit",
    "related_country":null,"merchant_allowed_countries":["DE"],"slug":"direct-debit",
    "instruction_text":"Simply enter the keys from your Paymill account, or  create a new Paymill account.",
    "info_url":"https:\/\/getpayever.com\/payment\/direct-debit\/",
    "thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/0281290f4dcd9cb441750563b7f55031.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/2d6afcda9abaf5d1ad7b92d24fb8d538.png",
    "min":0,"max":10000},
  {
    "name":"PayPal",
    "description_offer":"\u003Cp\u003EPayPal - Simply convenient.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EOffer your customers the popular payment method of PayPal. In most cases, you pay only 1.9% + 0.35\u20ac per transaction and even less if you sell more. And, of course, it is possible to use your existing PayPal account.\u003C\/p\u003E",
    "id":27,"status":"active",
    "variable_fee":1.9,"fixed_fee":0.35,"contract_length":0,"payment_method":"paypal",
    "related_country":null,"merchant_allowed_countries":[],"slug":"paypal",
    "instruction_text":"Simply connect your PayPal and payever accounts, or  create a new PayPal account.",
    "info_url":"https:\/\/getpayever.com\/payment\/paypal\/",
    "thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/dbbdbb3c5a0706871ebceb66dc3cce12.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/a043b4dc7b3b8bd3015b5623a4bf77ef.png",
    "min":0.02,"max":10000},
  {
    "name":"Credit Card",
    "description_offer":"Accept all Credit Card payments with Stripe.",
    "description_fee":"\u003Cp\u003ECredit card fees are only 2.9% + 0.30\u20ac per successful transaction.\u003C\/p\u003E",
    "id":28,"status":"active",
    "variable_fee":2.9,"fixed_fee":0.25,"contract_length":0,"payment_method":"stripe",
    "related_country":null,"merchant_allowed_countries":[],"slug":"credit-card",
    "instruction_text":"Simply connect your Stripe and payever accounts, or create a new Stripe account.",
    "info_url":"https:\/\/getpayever.com\/payment\/credit-card\/",
    "thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/2b25fe7d2e41fd670b526d07d60b1309.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/7fdf6986c90db505d5395881da25e0d8.png",
    "min":0.5,"max":100000},
  {
    "name":"Santander Installments",
    "description_offer":"\u003Cp\u003EAccept installment starting from 99\u20ac and up with Santander Installments. Maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 99\u20ac and up with a maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "id":29,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_installment",
    "related_country":"DE",
    "merchant_allowed_countries":["DK",
      "DE",
      "FI",
      "NO",
      "AT",
      "PT",
      "SE",
      "CH",
      "ES"],"slug":"santander-installments",
    "instruction_text":"Simply enter the credentials of your merchant account with Santander, or apply for a new account at Santander Bank.",
    "info_url":"https:\/\/getpayever.com\/payment\/installments\/",
    "thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/a8c61c9eaa6c98c7dfa38a43db07cc81.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/11044a6c5a825cff2f791e2508260ee1.png",
    "min":99,"max":100000,"related_country_name":"Germany"
  }
  ,
  {
    "name":"POS Santander Installments",
    "description_offer":"\u003Cp\u003EAccept installments offline. No expensive equipment needed.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 99\u20ac and up with a maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "id":30,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_pos_installment",
    "related_country":"DE",
    "merchant_allowed_countries":["DE"],"slug":"pos-santander-installments",
    "instruction_text":"Simply enter the credentials of your merchant account with Santander, or apply for a new account at Santander Bank.",
    "info_url":"https:\/\/getpayever.com\/payment\/installments\/",
    "thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/241291f3312765c5ca92be46e5c92bfc.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/e53ed9acd119972a2dd37d244ad7f51a.png",
    "min":99,"max":100000,"related_country_name":"Germany"
  }
  ,
  {
    "name":"Santander Installments Norway",
    "description_offer":"\u003Cp\u003EVi gir deg mulighet til \u00e5 enten utsette betalingen eller \u00e5 dele opp betalingen med faste bel\u00f8p hver m\u00e5ned i samarbeid med Santander Consumer Bank.&nbsp;\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 1.990 NOK and up with a maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "id":31,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_installment_no",
    "related_country":"NO",
    "merchant_allowed_countries":["DK",
      "DE",
      "FI",
      "NO",
      "AT",
      "SE",
      "CH",
      "ES"],"slug":"santander-installment-norway",
    "instruction_text":"Simply enter the credentials of your merchant account with Santander, or apply for a new account at Santander Bank.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/c9e7f915a8b14275d66cb1fc872e1a12.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/7208b36624fc5cef28b262d768c0d05d.png",
    "min":205.5615,"max":8263.7799,"related_country_name":"Norway"
  }
  ,/*
  {
    "name":"POS Santander Installments Norway",
    "description_offer":"\u003Cp\u003EVi gir deg mulighet til \u00e5 enten utsette betalingen eller \u00e5 dele opp betalingen med faste bel\u00f8p hver m\u00e5ned i samarbeid med Santander Consumer Bank.&nbsp;\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 1.990 NOK and up with a maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "id":32,"status":"disabled",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_pos_installment_no",
    "related_country":"NO",
    "merchant_allowed_countries":["DK",
      "DE",
      "FI",
      "NO",
      "AT",
      "SE",
      "CH",
      "ES"],"slug":"pos-santander-ratenkauf-nordics",
    "instruction_text":"Simply enter the credentials of your merchant account with Santander, or apply for a new account at Santander Bank.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/aab1b65fb4e66fc78dd2a5923b4a3626.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/eae16d621c6121d676f47267324e5b63.png",
    "min":205.5615,"max":8263.7799,"related_country_name":"Norway"
  }
  ,*/
  {
    "name":"Santander Invoice Norway",
    "description_offer":"\u003Cp\u003EKj\u00f8p n\u00e5 - betal etter levering. Fakturaen sendes p\u00e5 epost fra Santander Consumer Bank.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 199 NOK and up with a maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "id":35,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_invoice_no",
    "related_country":"NO",
    "merchant_allowed_countries":["NO"],"slug":"santander-invoice-nordics",
    "instruction_text":"Simply enter the credentials of your merchant account with Santander, or apply for a new account at Santander Bank.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/dfcc5ffe710133a47825060b0550ec83.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/42c426e43257e05c319d8fee502dc7df.png",
    "min":20.5562,"max":2065.945,"related_country_name":"Norway"
  }
  ,/*
  {
    "name":"POS Santander Invoice Norway",
    "description_offer":"\u003Cp\u003EKj\u00f8p n\u00e5 - betal etter levering. Fakturaen sendes p\u00e5 epost fra Santander Consumer Bank.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 199 NOK and up with a maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "id":36,"status":"disabled",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_pos_invoice_no",
    "related_country":"NO",
    "merchant_allowed_countries":["DK",
      "DE",
      "FI",
      "NO",
      "AT",
      "SE",
      "CH",
      "ES"],"slug":"pos-santander-invoice-nordics",
    "instruction_text":"Simply enter the credentials of your merchant account with Santander, or apply for a new account at Santander Bank.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/9d80c6c6f298c97f1ec9048cb60dead3.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/b32618047c8262cfd5d56f60972b2ad3.png",
    "min":20.5562,"max":2065.945,"related_country_name":"Norway"
  }
  ,*/
  {
    "name":"Santander Installments Denmark",
    "description_offer":"\u003Cp\u003EMake purchases worth 2000 DKK and up with Santander Installments. Maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 2000 DKK and up with a maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "id":37,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_installment_dk",
    "related_country":"DK",
    "merchant_allowed_countries":["DK",
      "DE",
      "FI",
      "NO",
      "AT",
      "SE",
      "CH",
      "ES"],"slug":"santander-ratenkauf-dk",
    "instruction_text":"Instruction for Payment Method \"Santander Ratenkauf Denmark\"",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/4f5c56f959a3423abd6c59fec15c312f.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/8ea99a00813543516af053c8012c5d6d.png",
    "min":201.1047,"max":13406.9824,"related_country_name":"Denmark"
  }
  ,
  {
    "name":"Santander Installments Sweden",
    "description_offer":"\u003Cp\u003EMake purchases worth 540 SEK and up with Santander Installments. Maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 540 SEK and up with a maximum annual percentage rate of 9.9% (6 - 72 monthly payments).\u003C\/p\u003E",
    "id":39,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_installment_se",
    "related_country":"SE",
    "merchant_allowed_countries":["SE",
      "DE",
      "DK",
      "NO",
      "ES",
      "AT",
      "FI",
      "CH"],"slug":"santander-installment-sweden",
    "instruction_text":"Instruction for Payment Method \"Santander Ratenkauf Sweden\"",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/56ab63cae3ee7fc4c2f1133bcb0d7629.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/05c416c63bcbbc2584bf96b1293773ce.png",
    "min":51.3919,"max":9517.0117,"related_country_name":"Sweden"
  }
  ,
  {
    "name":"PayEx Invoice",
    "description_offer":"\u003Cp\u003ESimply let your customers pay after delivery. You receive your payout before the customer pays the invoice.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003E\u003C\/p\u003E",
    "id":40,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"payex_faktura",
    "related_country":"SE",
    "merchant_allowed_countries":["SE"],"slug":"payex-faktura",
    "instruction_text":"\u003Cp\u003ESimply enter your account number and the encryption key of your PayEx account.\u003C\/p\u003E\n\u003Cp\u003EPayEx Faktura(SE) service is available to Swedish end customers in Swedish currency-Swedish Krona (SEK)\n\u003C\/p\u003E\nIf you have any questions regarding your PayEx account please contact PayEx at 0498-20 29 45 (Mo-Fr 08:00-17:00).",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/42bfd233104249cec40799d1bfaf3ed7.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/5862fe6e23c63acac4648cbfd789cbaf.png",
    "min":0,"max":4758.5058,"related_country_name":"Sweden"
  }
  ,
  {
    "name":"Santander DE Comfort card plus",
    "description_offer":"With ComfortCard Plus your customers get a Maestro card which gives them an extra budget.",
    "description_fee":"Santander DE Comfort card plus description fee",
    "id":41,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_ccp_installment",
    "related_country":"DE",
    "merchant_allowed_countries":["DE"],"slug":"santander-ccp-installment",
    "instruction_text":"Instruction for Payment Method \"Santander Installments Credit card Plus, Germany\"",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/c8e2dbdcc6b901fd377399f30dbc5f2f.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/b2399ccf26c027a946054e10fff05ab8.png",
    "min":99,"max":100000,"related_country_name":"Germany"
  }
  ,
  {
    "name":"PayEx Credit Card",
    "description_offer":"\u003Cp\u003ESimply let your customers pay&nbsp;by&nbsp;credit card. We accept MasterCard, Visa, American Express and many more.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003E\u003C\/p\u003E",
    "id":42,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"payex_creditcard",
    "related_country":"SE",
    "merchant_allowed_countries":["SE",
      "DK",
      "NO",
      "FI"],"slug":"payex-creditcard",
    "instruction_text":"\u003Cp\u003ESimply enter your account number and the encryption key of your PayEx account.\u003C\/p\u003E\n\u003Cp\u003EPayEx Faktura(SE) service is available to Swedish end customers in Swedish currency-Swedish Krona (SEK)\n\u003C\/p\u003E\nIf you have any questions regarding your PayEx account please contact PayEx at 0498-20 29 45 (Mo-Fr 08:00-17:00).",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/828415a9a6777b722568fab193730806.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/e8b4f903109f9676e71e3df63347dda2.png",
    "min":0,"max":100000,"related_country_name":"Sweden"
  }
  ,
  {
    "name":"Stripe DirectDebit",
    "description_offer":"Accept SEPA Direct Debit Payments with Stripe.",
    "description_fee":"Stripe DirectDebit description fee",
    "id":43,"status":"disabled",
    "variable_fee":2.9,"fixed_fee":0.25,"contract_length":0,"payment_method":"stripe_directdebit",
    "related_country":null,"merchant_allowed_countries":[],"slug":"stripe-directdebit",
    "instruction_text":"Simply connect your Stripe and payever accounts, or create a new Stripe account.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/7e8021774db236b3bec395d05212684e.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/fdb36e17b74cb411fe1f616c928c7494.png",
    "min":0,"max":100000},
  {
    "name":"Santander DE Invoice",
    "description_offer":"Let your customers pay with the Santander Invoice payment option.",
    "description_fee":"Santander DE Invoice description fee",
    "id":45,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_invoice_de",
    "related_country":"DE",
    "merchant_allowed_countries":["DE"],"slug":"santander-invoice-de",
    "instruction_text":"Just enter the keys of your Santander Invoice account. Or apply in order to open a new account.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/160090779ab75ca35704197d379c774c.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/26470f3801e6d92bba760a214cf8fb89.png",
    "min":0,"max":750,"related_country_name":"Germany"
  }
  ,
  {
    "name":"POS Santander Installments Sweden",
    "description_offer":"\u003Cp\u003EAccept installments offline. No expensive equipment needed.\u003C\/p\u003E",
    "description_fee":"\u003Cp\u003EAccept Santander Installments at no cost to you for purchases starting at 540 SEK in your local store\u003C\/p\u003E",
    "id":46,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_pos_installment_se",
    "related_country":"SE",
    "merchant_allowed_countries":["SE"],"slug":"pos-santander-installment-sweden",
    "instruction_text":"payment_options.instructions.text.santander_pos_installment_se",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/da752000dc6764c44971d7197f4952f5.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/resolve\/payment_option.icon\/219d0a11c1474b92a7e5dae59356f368.png",
    "min":51.3919,"max":9517.0117,"related_country_name":"Sweden"
  }
  ,
  {
    "name":"Santander Factoring",
    "description_offer":"Santander Factoring description",
    "description_fee":"santander_factoring_de.description_fee",
    "id":47,"status":"active",
    "variable_fee":0,"fixed_fee":0,"contract_length":0,"payment_method":"santander_factoring_de",
    "related_country":"DE",
    "merchant_allowed_countries":["DE"],"slug":"santander-factoring-de",
    "instruction_text":"Just enter the keys of your Santander Invoice account. Or apply in order to open a new account.",
    "info_url":null,"thumbnail1":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/775f7c1ef66085c030d05e0750de35a0.png",
    "thumbnail2":"https:\/\/stage.payever.de\/media\/cache\/payment_option.icon\/93546f1fab74abeea50e5ad0337e1820.png",
    "min":20,"max":1000,"related_country_name":"Germany"
  }
];

export const usages: any = {
  "payment_methods": [
    "santander_ccp_installment",
    "santander_pos_installment",
    "santander_factoring_de",
    "santander_installment",
    "paymill_directdebit",
    "paypal",
    "santander_invoice_de",
    "paymill_creditcard",
    "stripe",
    "invoice",
    "sofort",
    "cash"],
  "channels":["magento",
    "wooCommerce",
    "finance_express",
    "pos",
    "store",
    "shopify",
    "facebook",
    "other_shopsystem",
    "marketing"],
  "statuses":[{
    "key":"STATUS_CANCELLED",
    "name":"Cancelled"
  }
    ,
    {
      "key":"STATUS_FAILED",
      "name":"Failed"
    }
    ,
    {
      "key":"STATUS_DECLINED",
      "name":"Declined"
    }
    ,
    {
      "key":"STATUS_IN_PROCESS",
      "name":"In progress"
    }
    ,
    {
      "key":"STATUS_PAID",
      "name":"Paid"
    }
    ,
    {
      "key":"STATUS_REFUNDED",
      "name":"Refunded"
    }
    ,
    {
      "key":"STATUS_ACCEPTED",
      "name":"Accepted"
    }
    ,
    {
      "key":"STATUS_NEW",
      "name":"New"
    }
  ],
  "stores":[
    {
      "id":"130734",
      "name":"Store"
    }
    ,
    {
      "id":"72525",
      "name":"marketing.name"
    }
    ,
    {
      "id":"922",
      "name":"Marketing"
    }
    ,
    {
      "id":"131325",
      "name":"Store"
    }
    ,
    {
      "id":"72734",
      "name":"marketing.name"
    }
    ,
    {
      "id":"951",
      "name":"Store"
    }
    ,
    {
      "id":"131330",
      "name":"StageTest"
    }
    ,
    {
      "id":"73622",
      "name":"marketing.name"
    }
    ,
    {
      "id":"978",
      "name":"Store"
    }
    ,
    {
      "id":"131441",
      "name":"Store"
    }
    ,
    {
      "id":"74325",
      "name":"marketing.name"
    }
    ,
    {
      "id":"999",
      "name":"Marketing"
    }
    ,
    {
      "id":"131455",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"77483",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1005",
      "name":"Marketing"
    }
    ,
    {
      "id":"131459",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"84800",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1027",
      "name":"Marketing"
    }
    ,
    {
      "id":"131463",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"86997",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1035",
      "name":"Marketing"
    }
    ,
    {
      "id":"62",
      "name":"Store"
    }
    ,
    {
      "id":"131467",
      "name":"Store"
    }
    ,
    {
      "id":"89649",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1050",
      "name":"Marketing"
    }
    ,
    {
      "id":"72",
      "name":"Store1"
    }
    ,
    {
      "id":"131472",
      "name":"tester11"
    }
    ,
    {
      "id":"89724",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1065",
      "name":"Marketing"
    }
    ,
    {
      "id":"93",
      "name":"Weebly"
    }
    ,
    {
      "id":"133540",
      "name":"Test"
    }
    ,
    {
      "id":"89782",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1084",
      "name":"Marketing"
    }
    ,
    {
      "id":"100",
      "name":"Facebook"
    }
    ,
    {
      "id":"134389",
      "name":"sdfsdfsd"
    }
    ,
    {
      "id":"89788",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1114",
      "name":"Marketing"
    }
    ,
    {
      "id":"118",
      "name":"Facebook"
    }
    ,
    {
      "id":"135418",
      "name":"dfdsf"
    }
    ,
    {
      "id":"89816",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1141",
      "name":"Marketing"
    }
    ,
    {
      "id":"131",
      "name":"Facebook"
    }
    ,
    {
      "id":"135423",
      "name":"asdasd"
    }
    ,
    {
      "id":"89838",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1150",
      "name":"Marketing"
    }
    ,
    {
      "id":"138",
      "name":"Facebook"
    }
    ,
    {
      "id":"135660",
      "name":"sdf"
    }
    ,
    {
      "id":"89843",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1157",
      "name":"Marketing"
    }
    ,
    {
      "id":"153",
      "name":"Facebook"
    }
    ,
    {
      "id":"136220",
      "name":"new"
    }
    ,
    {
      "id":"89857",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1166",
      "name":"Marketing"
    }
    ,
    {
      "id":"161",
      "name":"Facebook"
    }
    ,
    {
      "id":"138265",
      "name":"test"
    }
    ,
    {
      "id":"89907",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1173",
      "name":"Marketing"
    }
    ,
    {
      "id":"165",
      "name":"Facebook"
    }
    ,
    {
      "id":"140282",
      "name":"ыфвыф"
    }
    ,
    {
      "id":"90097",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1182",
      "name":"Marketing"
    }
    ,
    {
      "id":"181",
      "name":"Facebook"
    }
    ,
    {
      "id":"141959",
      "name":"shopSergey"
    }
    ,
    {
      "id":"92516",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1189",
      "name":"Marketing"
    }
    ,
    {
      "id":"187",
      "name":"Store"
    }
    ,
    {
      "id":"141964",
      "name":"hi guys"
    }
    ,
    {
      "id":"92527",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1199",
      "name":"Marketing"
    }
    ,
    {
      "id":"205",
      "name":"Store"
    }
    ,
    {
      "id":"144731",
      "name":"testmenu"
    }
    ,
    {
      "id":"92721",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1216",
      "name":"Marketing"
    }
    ,
    {
      "id":"210",
      "name":"Facebook"
    }
    ,
    {
      "id":"144961",
      "name":"ertret"
    }
    ,
    {
      "id":"93042",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1234",
      "name":"Marketing"
    }
    ,
    {
      "id":"228",
      "name":"Facebook"
    }
    ,
    {
      "id":"145524",
      "name":"gggg"
    }
    ,
    {
      "id":"93049",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1238",
      "name":"Marketing"
    }
    ,
    {
      "id":"243",
      "name":"marketing shop 1"
    }
    ,
    {
      "id":"145923",
      "name":"fghfgh"
    }
    ,
    {
      "id":"93380",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1254",
      "name":"Marketing"
    }
    ,
    {
      "id":"253",
      "name":"Marketing"
    }
    ,
    {
      "id":"146468",
      "name":"teset"
    }
    ,
    {
      "id":"95371",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1259",
      "name":"Marketing"
    }
    ,
    {
      "id":"272",
      "name":"Marketing"
    }
    ,
    {
      "id":"148477",
      "name":"marketing.name"
    }
    ,
    {
      "id":"97103",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1263",
      "name":"Marketing"
    }
    ,
    {
      "id":"285",
      "name":"Marketing"
    }
    ,
    {
      "id":"149424",
      "name":"marketing.name"
    }
    ,
    {
      "id":"98701",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1271",
      "name":"Marketing"
    }
    ,
    {
      "id":"299",
      "name":"Marketing"
    }
    ,
    {
      "id":"151307",
      "name":"kk"
    }
    ,
    {
      "id":"99506",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1306",
      "name":"Marketing"
    }
    ,
    {
      "id":"319",
      "name":"Marketing"
    }
    ,
    {
      "id":"155076",
      "name":"kkstore"
    }
    ,
    {
      "id":"100211",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1311",
      "name":"Store"
    }
    ,
    {
      "id":"324",
      "name":"Marketing"
    }
    ,
    {
      "id":"160272",
      "name":"serg"
    }
    ,
    {
      "id":"100286",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1325",
      "name":"Store"
    }
    ,
    {
      "id":"350",
      "name":"Marketing"
    }
    ,
    {
      "id":"161027",
      "name":"marketing.name"
    }
    ,
    {
      "id":"101135",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1342",
      "name":"Marketing"
    }
    ,
    {
      "id":"355",
      "name":"Marketing"
    }
    ,
    {
      "id":"161360",
      "name":"marketing.name"
    }
    ,
    {
      "id":"103955",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1377",
      "name":"Marketing"
    }
    ,
    {
      "id":"397",
      "name":"Marketing"
    }
    ,
    {
      "id":"162143",
      "name":"jj"
    }
    ,
    {
      "id":"106695",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1393",
      "name":"Weebly"
    }
    ,
    {
      "id":"403",
      "name":"Marketing"
    }
    ,
    {
      "id":"162841",
      "name":"Pos"
    }
    ,
    {
      "id":"108577",
      "name":"Pos"
    }
    ,
    {
      "id":"1538",
      "name":"Marketing"
    }
    ,
    {
      "id":"407",
      "name":"Marketing"
    }
    ,
    {
      "id":"163458",
      "name":"Pos"
    }
    ,
    {
      "id":"108600",
      "name":"Pos"
    }
    ,
    {
      "id":"1899",
      "name":"Facebook"
    }
    ,
    {
      "id":"414",
      "name":"Marketing"
    }
    ,
    {
      "id":"164550",
      "name":"sldkfjsdf"
    }
    ,
    {
      "id":"108627",
      "name":"Pos"
    }
    ,
    {
      "id":"1952",
      "name":"Marketing"
    }
    ,
    {
      "id":"424",
      "name":"Marketing"
    }
    ,
    {
      "id":"168561",
      "name":"Pos"
    }
    ,
    {
      "id":"109543",
      "name":"marketing.name"
    }
    ,
    {
      "id":"2014",
      "name":"shryj"
    }
    ,
    {
      "id":"454",
      "name":"Marketing"
    }
    ,
    {
      "id":"169575",
      "name":"zx"
    }
    ,
    {
      "id":"111230",
      "name":"Pos"
    }
    ,
    {
      "id":"2501",
      "name":"local.test.create"
    }
    ,
    {
      "id":"482",
      "name":"Store"
    }
    ,
    {
      "id":"169730",
      "name":"zxc"
    }
    ,
    {
      "id":"113945",
      "name":"Pos"
    }
    ,
    {
      "id":"2668",
      "name":"new"
    }
    ,
    {
      "id":"489",
      "name":"Marketing"
    }
    ,
    {
      "id":"172228",
      "name":"marketing.name"
    }
    ,
    {
      "id":"122118",
      "name":"Store"
    }
    ,
    {
      "id":"3244",
      "name":"Marketing"
    }
    ,
    {
      "id":"494",
      "name":"Marketing"
    }
    ,
    {
      "id":"172383",
      "name":"Alexey"
    }
    ,
    {
      "id":"124663",
      "name":"Store"
    }
    ,
    {
      "id":"5933",
      "name":"Δ"
    }
    ,
    {
      "id":"505",
      "name":"Marketing"
    }
    ,
    {
      "id":"125478",
      "name":"Store"
    }
    ,
    {
      "id":"8352",
      "name":"marketing.name"
    }
    ,
    {
      "id":"589",
      "name":"Marketing"
    }
    ,
    {
      "id":"125816",
      "name":"Pos"
    }
    ,
    {
      "id":"8536",
      "name":"marketing.name"
    }
    ,
    {
      "id":"733",
      "name":"Marketing"
    }
    ,
    {
      "id":"126582",
      "name":"Store"
    }
    ,
    {
      "id":"19181",
      "name":"XXXLutz"
    }
    ,
    {
      "id":"743",
      "name":"Marketing"
    }
    ,
    {
      "id":"126727",
      "name":"Store"
    }
    ,
    {
      "id":"20503",
      "name":"marketing.name"
    }
    ,
    {
      "id":"768",
      "name":"Marketing"
    }
    ,
    {
      "id":"127344",
      "name":"Pos"
    }
    ,
    {
      "id":"27116",
      "name":"iPhone 6s"
    }
    ,
    {
      "id":"780",
      "name":"Store"
    }
    ,
    {
      "id":"128114",
      "name":"Pos"
    }
    ,
    {
      "id":"45395",
      "name":"marketing.name"
    }
    ,
    {
      "id":"831",
      "name":"Marketing"
    }
    ,
    {
      "id":"128384",
      "name":"Store"
    }
    ,
    {
      "id":"62880",
      "name":"ΔiPhone 6s"
    }
    ,
    {
      "id":"853",
      "name":"Store"
    }
    ,
    {
      "id":"128759",
      "name":"Store"
    }
    ,
    {
      "id":"70538",
      "name":"marketing.name"
    }
    ,
    {
      "id":"872",
      "name":"Store"
    }
    ,
    {
      "id":"128929",
      "name":"Store"
    }
    ,
    {
      "id":"72507",
      "name":"marketing.name"
    }
    ,
    {
      "id":"903",
      "name":"Marketing"
    }
    ,
    {
      "id":"129097",
      "name":"Store"
    }
    ,
    {
      "id":"72512",
      "name":"marketing.name"
    }
    ,
    {
      "id":"914",
      "name":"Marketing"
    }
    ,
    {
      "id":"129469",
      "name":"Store"
    }
    ,
    {
      "id":"72519",
      "name":"marketing.name"
    }
    ,
    {
      "id":"918",
      "name":"Marketing"
    }
    ,
    {
      "id":"131286",
      "name":"Store"
    }
    ,
    {
      "id":"72675",
      "name":"marketing.name"
    }
    ,
    {
      "id":"924",
      "name":"Store"
    }
    ,
    {
      "id":"131327",
      "name":"Store"
    }
    ,
    {
      "id":"72777",
      "name":"marketing.name"
    }
    ,
    {
      "id":"956",
      "name":"Store"
    }
    ,
    {
      "id":"131331",
      "name":"Tester!"
    }
    ,
    {
      "id":"73638",
      "name":"marketing.name"
    }
    ,
    {
      "id":"979",
      "name":"Store"
    }
    ,
    {
      "id":"131442",
      "name":"Store"
    }
    ,
    {
      "id":"74609",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1000",
      "name":"Marketing"
    }
    ,
    {
      "id":"131456",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"80266",
      "name":"Sports & Outdoor item #3"
    }
    ,
    {
      "id":"1024",
      "name":"Marketing"
    }
    ,
    {
      "id":"131460",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"85591",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1030",
      "name":"Marketing"
    }
    ,
    {
      "id":"131464",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"87013",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1036",
      "name":"Marketing"
    }
    ,
    {
      "id":"69",
      "name":"Facebook"
    }
    ,
    {
      "id":"131468",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"89721",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1051",
      "name":"Marketing"
    }
    ,
    {
      "id":"79",
      "name":"Facebook"
    }
    ,
    {
      "id":"132309",
      "name":"Store"
    }
    ,
    {
      "id":"89725",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1066",
      "name":"Marketing"
    }
    ,
    {
      "id":"94",
      "name":"Weebly"
    }
    ,
    {
      "id":"134112",
      "name":"adasdas"
    }
    ,
    {
      "id":"89783",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1101",
      "name":"Marketing"
    }
    ,
    {
      "id":"105",
      "name":"Facebook"
    }
    ,
    {
      "id":"134580",
      "name":"sadasdasd"
    }
    ,
    {
      "id":"89797",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1129",
      "name":"Facebook"
    }
    ,
    {
      "id":"119",
      "name":"Facebook"
    }
    ,
    {
      "id":"135420",
      "name":"asdas"
    }
    ,
    {
      "id":"89820",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1142",
      "name":"Marketing"
    }
    ,
    {
      "id":"132",
      "name":"Facebook"
    }
    ,
    {
      "id":"135424",
      "name":"adasdasd"
    }
    ,
    {
      "id":"89839",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1153",
      "name":"Marketing"
    }
    ,
    {
      "id":"139",
      "name":"Store"
    }
    ,
    {
      "id":"135661",
      "name":"ff"
    }
    ,
    {
      "id":"89844",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1158",
      "name":"Marketing"
    }
    ,
    {
      "id":"154",
      "name":"Facebook"
    }
    ,
    {
      "id":"137708",
      "name":"sdf"
    }
    ,
    {
      "id":"89859",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1167",
      "name":"Store"
    }
    ,
    {
      "id":"162",
      "name":"Facebook"
    }
    ,
    {
      "id":"138266",
      "name":"sdf"
    }
    ,
    {
      "id":"90027",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1174",
      "name":"Marketing"
    }
    ,
    {
      "id":"166",
      "name":"Weebly"
    }
    ,
    {
      "id":"140877",
      "name":"123"
    }
    ,
    {
      "id":"91748",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1183",
      "name":"Marketing"
    }
    ,
    {
      "id":"182",
      "name":"Facebook"
    }
    ,
    {
      "id":"141961",
      "name":"sergey"
    }
    ,
    {
      "id":"92517",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1190",
      "name":"Marketing"
    }
    ,
    {
      "id":"193",
      "name":"Facebook"
    }
    ,
    {
      "id":"141965",
      "name":"hi guys"
    }
    ,
    {
      "id":"92529",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1213",
      "name":"Marketing"
    }
    ,
    {
      "id":"206",
      "name":"Store"
    }
    ,
    {
      "id":"144773",
      "name":"ggg"
    }
    ,
    {
      "id":"93036",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1231",
      "name":"Marketing"
    }
    ,
    {
      "id":"212",
      "name":"Facebook"
    }
    ,
    {
      "id":"144962",
      "name":"fff"
    }
    ,
    {
      "id":"93043",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1235",
      "name":"Marketing"
    }
    ,
    {
      "id":"235",
      "name":"Store"
    }
    ,
    {
      "id":"145525",
      "name":"dsgsdg"
    }
    ,
    {
      "id":"93306",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1247",
      "name":"Marketing"
    }
    ,
    {
      "id":"244",
      "name":"marketing shop 2"
    }
    ,
    {
      "id":"146362",
      "name":"marketing.name"
    }
    ,
    {
      "id":"93381",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1255",
      "name":"Marketing"
    }
    ,
    {
      "id":"254",
      "name":"Marketing"
    }
    ,
    {
      "id":"146486",
      "name":"fdgdfg"
    }
    ,
    {
      "id":"95373",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1260",
      "name":"Marketing"
    }
    ,
    {
      "id":"282",
      "name":"Marketing"
    }
    ,
    {
      "id":"148478",
      "name":"marketing.name"
    }
    ,
    {
      "id":"98117",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1266",
      "name":"Marketing"
    }
    ,
    {
      "id":"286",
      "name":"Marketing"
    }
    ,
    {
      "id":"149692",
      "name":"TestStore"
    }
    ,
    {
      "id":"98924",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1302",
      "name":"Marketing"
    }
    ,
    {
      "id":"300",
      "name":"Marketing"
    }
    ,
    {
      "id":"151783",
      "name":"CHEck"
    }
    ,
    {
      "id":"99507",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1307",
      "name":"Marketing"
    }
    ,
    {
      "id":"320",
      "name":"Marketing"
    }
    ,
    {
      "id":"156658",
      "name":"marketing.name"
    }
    ,
    {
      "id":"100212",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1322",
      "name":"Facebook"
    }
    ,
    {
      "id":"325",
      "name":"Marketing"
    }
    ,
    {
      "id":"160599",
      "name":"marketing.name"
    }
    ,
    {
      "id":"100287",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1339",
      "name":"Marketing"
    }
    ,
    {
      "id":"352",
      "name":"Marketing"
    }
    ,
    {
      "id":"161099",
      "name":"marketing.name"
    }
    ,
    {
      "id":"101330",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1355",
      "name":"Marketing"
    }
    ,
    {
      "id":"356",
      "name":"Marketing"
    }
    ,
    {
      "id":"161367",
      "name":"marketing.name"
    }
    ,
    {
      "id":"104235",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1386",
      "name":"Marketing"
    }
    ,
    {
      "id":"398",
      "name":"Marketing"
    }
    ,
    {
      "id":"162420",
      "name":"Pos"
    }
    ,
    {
      "id":"108558",
      "name":"Pos"
    }
    ,
    {
      "id":"1394",
      "name":"Weebly"
    }
    ,
    {
      "id":"404",
      "name":"Marketing"
    }
    ,
    {
      "id":"163175",
      "name":"Pos"
    }
    ,
    {
      "id":"108590",
      "name":"Pos"
    }
    ,
    {
      "id":"1617",
      "name":"Store"
    }
    ,
    {
      "id":"408",
      "name":"Marketing"
    }
    ,
    {
      "id":"164125",
      "name":"Pos"
    }
    ,
    {
      "id":"108601",
      "name":"Pos"
    }
    ,
    {
      "id":"1904",
      "name":"Facebook"
    }
    ,
    {
      "id":"415",
      "name":"Marketing"
    }
    ,
    {
      "id":"167800",
      "name":"Slava"
    }
    ,
    {
      "id":"108642",
      "name":"Pos"
    }
    ,
    {
      "id":"1953",
      "name":"Marketing"
    }
    ,
    {
      "id":"438",
      "name":"Marketing"
    }
    ,
    {
      "id":"169280",
      "name":"lllllllllllll"
    }
    ,
    {
      "id":"110451",
      "name":"marketing.name"
    }
    ,
    {
      "id":"2019",
      "name":"New"
    }
    ,
    {
      "id":"464",
      "name":"Marketing"
    }
    ,
    {
      "id":"169583",
      "name":"z1"
    }
    ,
    {
      "id":"112266",
      "name":"Pos"
    }
    ,
    {
      "id":"2569",
      "name":"11212"
    }
    ,
    {
      "id":"483",
      "name":"Comspot"
    }
    ,
    {
      "id":"170345",
      "name":"test 111"
    }
    ,
    {
      "id":"113950",
      "name":"Pos"
    }
    ,
    {
      "id":"2931",
      "name":"ΔExample: A hot cup of coffee"
    }
    ,
    {
      "id":"490",
      "name":"Marketing"
    }
    ,
    {
      "id":"172380",
      "name":"some_store_name"
    }
    ,
    {
      "id":"123613",
      "name":"Store"
    }
    ,
    {
      "id":"3259",
      "name":"Marketing"
    }
    ,
    {
      "id":"502",
      "name":"Marketing"
    }
    ,
    {
      "id":"172530",
      "name":"serg test"
    }
    ,
    {
      "id":"124666",
      "name":"Store"
    }
    ,
    {
      "id":"6741",
      "name":"PHILIPS 55PFK6500"
    }
    ,
    {
      "id":"507",
      "name":"Marketing"
    }
    ,
    {
      "id":"125762",
      "name":"Store"
    }
    ,
    {
      "id":"8353",
      "name":"marketing.name"
    }
    ,
    {
      "id":"637",
      "name":"Store"
    }
    ,
    {
      "id":"126480",
      "name":"Store"
    }
    ,
    {
      "id":"10746",
      "name":"XXXLutz"
    }
    ,
    {
      "id":"740",
      "name":"Marketing"
    }
    ,
    {
      "id":"126606",
      "name":"Pos"
    }
    ,
    {
      "id":"19182",
      "name":"XXXLutz"
    }
    ,
    {
      "id":"744",
      "name":"Marketing"
    }
    ,
    {
      "id":"126736",
      "name":"Store"
    }
    ,
    {
      "id":"20504",
      "name":"marketing.name"
    }
    ,
    {
      "id":"769",
      "name":"Marketing"
    }
    ,
    {
      "id":"127356",
      "name":"Store"
    }
    ,
    {
      "id":"29779",
      "name":"iPhone 6s"
    }
    ,
    {
      "id":"781",
      "name":"Marketing"
    }
    ,
    {
      "id":"128115",
      "name":"Pos"
    }
    ,
    {
      "id":"53516",
      "name":"Store"
    }
    ,
    {
      "id":"833",
      "name":"Marketing"
    }
    ,
    {
      "id":"128747",
      "name":"Store"
    }
    ,
    {
      "id":"63086",
      "name":"marketing.name"
    }
    ,
    {
      "id":"866",
      "name":"Marketing"
    }
    ,
    {
      "id":"128926",
      "name":"Store"
    }
    ,
    {
      "id":"70543",
      "name":"marketing.name"
    }
    ,
    {
      "id":"889",
      "name":"Marketing"
    }
    ,
    {
      "id":"128930",
      "name":"Store"
    }
    ,
    {
      "id":"72508",
      "name":"marketing.name"
    }
    ,
    {
      "id":"908",
      "name":"Marketing"
    }
    ,
    {
      "id":"129098",
      "name":"Store"
    }
    ,
    {
      "id":"72513",
      "name":"marketing.name"
    }
    ,
    {
      "id":"915",
      "name":"Marketing"
    }
    ,
    {
      "id":"129471",
      "name":"Store"
    }
    ,
    {
      "id":"72520",
      "name":"marketing.name"
    }
    ,
    {
      "id":"919",
      "name":"Marketing"
    }
    ,
    {
      "id":"131323",
      "name":"qwe"
    }
    ,
    {
      "id":"72676",
      "name":"marketing.name"
    }
    ,
    {
      "id":"931",
      "name":"Marketing"
    }
    ,
    {
      "id":"131328",
      "name":"asd"
    }
    ,
    {
      "id":"72778",
      "name":"marketing.name"
    }
    ,
    {
      "id":"957",
      "name":"Store"
    }
    ,
    {
      "id":"131332",
      "name":"Store"
    }
    ,
    {
      "id":"73639",
      "name":"Store"
    }
    ,
    {
      "id":"980",
      "name":"Store"
    }
    ,
    {
      "id":"131443",
      "name":"Store"
    }
    ,
    {
      "id":"77119",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1002",
      "name":"Marketing"
    }
    ,
    {
      "id":"131457",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"84488",
      "name":"Weebly"
    }
    ,
    {
      "id":"1025",
      "name":"Marketing"
    }
    ,
    {
      "id":"131461",
      "name":"sdfsdf"
    }
    ,
    {
      "id":"86283",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1032",
      "name":"Marketing"
    }
    ,
    {
      "id":"1",
      "name":"MyOnlineShops"
    }
    ,
    {
      "id":"131465",
      "name":"Store"
    }
    ,
    {
      "id":"87166",
      "name":"Store"
    }
    ,
    {
      "id":"1040",
      "name":"Store"
    }
    ,
    {
      "id":"70",
      "name":"Facebook"
    }
    ,
    {
      "id":"131470",
      "name":"sd"
    }
    ,
    {
      "id":"89722",
      "name":"marketing.name"
    }
    ,
    {
      "id":"1053",
      "name":"Marketing"
    }
    ,
    {
      "id":"80",
      "name":"Facebook"
    }
  ,
  {
    "id":"133013",
    "name":"Store"
  }
  ,
  {
    "id":"89780",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1067",
    "name":"Marketing"
  }
  ,
  {
    "id":"95",
    "name":"Store"
  }
  ,
  {
    "id":"134387",
    "name":"Test"
  }
  ,
  {
    "id":"89786",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1107",
    "name":"Weebly"
  }
  ,
  {
    "id":"116",
    "name":"Facebook"
  }
  ,
  {
    "id":"135183",
    "name":"test"
  }
  ,
  {
    "id":"89809",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1136",
    "name":"Marketing"
  }
  ,
  {
    "id":"120",
    "name":"Facebook"
  }
  ,
  {
    "id":"135421",
    "name":"sadasd"
  }
  ,
  {
    "id":"89830",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1143",
    "name":"Marketing"
  }
  ,
  {
    "id":"133",
    "name":"Weebly"
  }
  ,
  {
    "id":"135657",
    "name":"sdf"
  }
  ,
  {
    "id":"89841",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1154",
    "name":"Marketing"
  }
  ,
  {
    "id":"143",
    "name":"Facebook"
  }
  ,
  {
    "id":"135662",
    "name":"qwe"
  }
  ,
  {
    "id":"89845",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1164",
    "name":"Marketing"
  }
  ,
  {
    "id":"157",
    "name":"Facebook"
  }
  ,
  {
    "id":"138047",
    "name":"new store"
  }
  ,
  {
    "id":"89860",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1170",
    "name":"Facebook"
  }
  ,
  {
    "id":"163",
    "name":"Facebook"
  }
  ,
  {
    "id":"138267",
    "name":"new"
  }
  ,
  {
    "id":"90032",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1178",
    "name":"Weebly"
  }
  ,
  {
    "id":"168",
    "name":"Facebook"
  }
  ,
  {
    "id":"141895",
    "name":"test"
  }
  ,
  {
    "id":"91749",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1184",
    "name":"Marketing"
  }
  ,
  {
    "id":"183",
    "name":"Facebook"
  }
  ,
  {
    "id":"141962",
    "name":"serg"
  }
  ,
  {
    "id":"92518",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1195",
    "name":"Marketing"
  }
  ,
  {
    "id":"195",
    "name":"Facebook"
  }
  ,
  {
    "id":"141967",
    "name":"hi guys"
  }
  ,
  {
    "id":"92530",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1214",
    "name":"Marketing"
  }
  ,
  {
    "id":"207",
    "name":"Facebook"
  }
  ,
  {
    "id":"144774",
    "name":"hgfdh"
  }
  ,
  {
    "id":"93037",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1232",
    "name":"Marketing"
  }
  ,
  {
    "id":"213",
    "name":"Facebook"
  }
  ,
  {
    "id":"144963",
    "name":"fgdfgdg"
  }
  ,
  {
    "id":"93046",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1236",
    "name":"Marketing"
  }
  ,
  {
    "id":"236",
    "name":"Store"
  }
  ,
  {
    "id":"145903",
    "name":"dfgdg"
  }
  ,
  {
    "id":"93307",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1248",
    "name":"Marketing"
  }
  ,
  {
    "id":"245",
    "name":"marketing shop 3"
  }
  ,
  {
    "id":"146416",
    "name":"asd"
  }
  ,
  {
    "id":"93493",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1256",
    "name":"Marketing"
  }
  ,
  {
    "id":"259",
    "name":"Marketing"
  }
  ,
  {
    "id":"147163",
    "name":"marketing.name"
  }
  ,
  {
    "id":"95374",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1261",
    "name":"Marketing"
  }
  ,
  {
    "id":"283",
    "name":"Marketing"
  }
  ,
  {
    "id":"148480",
    "name":"marketing.name"
  }
  ,
  {
    "id":"98121",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1269",
    "name":"Marketing"
  }
  ,
  {
    "id":"287",
    "name":"Marketing"
  }
  ,
  {
    "id":"149708",
    "name":"marketing.name"
  }
  ,
  {
    "id":"98926",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1304",
    "name":"Marketing"
  }
  ,
  {
    "id":"305",
    "name":"Marketing"
  }
  ,
  {
    "id":"151785",
    "name":"test"
  }
  ,
  {
    "id":"100011",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1308",
    "name":"Marketing"
  }
  ,
  {
    "id":"322",
    "name":"Marketing"
  }
  ,
  {
    "id":"157930",
    "name":"Pos"
  }
  ,
  {
    "id":"100213",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1323",
    "name":"Store"
  }
  ,
  {
    "id":"326",
    "name":"Marketing"
  }
  ,
  {
    "id":"160771",
    "name":"marketing.name"
  }
  ,
  {
    "id":"100288",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1340",
    "name":"Marketing"
  }
  ,
  {
    "id":"353",
    "name":"Marketing"
  }
  ,
  {
    "id":"161358",
    "name":"marketing.name"
  }
  ,
  {
    "id":"101338",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1369",
    "name":"Marketing"
  }
  ,
  {
    "id":"362",
    "name":"Store"
  }
  ,
  {
    "id":"161379",
    "name":"marketing.name"
  }
  ,
  {
    "id":"104349",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1387",
    "name":"Marketing"
  }
  ,
  {
    "id":"399",
    "name":"Marketing"
  }
  ,
  {
    "id":"162599",
    "name":"kk"
  }
  ,
  {
    "id":"108569",
    "name":"Pos"
  }
  ,
  {
    "id":"1515",
    "name":"Marketing"
  }
  ,
  {
    "id":"405",
    "name":"Marketing"
  }
  ,
  {
    "id":"163176",
    "name":"Pos"
  }
  ,
  {
    "id":"108591",
    "name":"Pos"
  }
  ,
  {
    "id":"1618",
    "name":"Facebook"
  }
  ,
  {
    "id":"409",
    "name":"Marketing"
  }
  ,
  {
    "id":"164127",
    "name":"TestStoreName"
  }
  ,
  {
    "id":"108612",
    "name":"Pos"
  }
  ,
  {
    "id":"1915",
    "name":"Facebook"
  }
  ,
  {
    "id":"417",
    "name":"Marketing"
  }
  ,
  {
    "id":"167904",
    "name":"sdf"
  }
  ,
  {
    "id":"108700",
    "name":"Pos"
  }
  ,
  {
    "id":"1976",
    "name":"Marketing"
  }
  ,
  {
    "id":"451",
    "name":"Marketing"
  }
  ,
  {
    "id":"169571",
    "name":"test1"
  }
  ,
  {
    "id":"110452",
    "name":"marketing.name"
  }
  ,
  {
    "id":"2036",
    "name":"nre"
  }
  ,
  {
    "id":"474",
    "name":"Marketing"
  }
  ,
  {
    "id":"169728",
    "name":"z2"
  }
  ,
  {
    "id":"113373",
    "name":"marketing.name"
  }
  ,
  {
    "id":"2571",
    "name":"12121"
  }
  ,
  {
    "id":"484",
    "name":"Marketing"
  }
  ,
  {
    "id":"171313",
    "name":"Bulash Store"
  }
  ,
  {
    "id":"116270",
    "name":"Pos"
  }
  ,
  {
    "id":"2985",
    "name":"ΔApple Watch"
  }
  ,
  {
    "id":"492",
    "name":"Marketing"
  }
  ,
  {
    "id":"172381",
    "name":"Alexey"
  }
  ,
  {
    "id":"123614",
    "name":"Store"
  }
  ,
  {
    "id":"3865",
    "name":"12121"
  }
  ,
  {
    "id":"503",
    "name":"Marketing"
  }
  ,
  {
    "id":"172985",
    "name":"dm test"
  }
  ,
  {
    "id":"124667",
    "name":"Store"
  }
  ,
  {
    "id":"7540",
    "name":"marketing.name"
  }
  ,
  {
    "id":"535",
    "name":"Marketing"
  }
  ,
  {
    "id":"125805",
    "name":"Store"
  }
  ,
  {
    "id":"8451",
    "name":"marketing.name"
  }
  ,
  {
    "id":"655",
    "name":"Marketing"
  }
  ,
  {
    "id":"126481",
    "name":"marketing.name"
  }
  ,
  {
    "id":"16125",
    "name":"marketing.name"
  }
  ,
  {
    "id":"741",
    "name":"Marketing"
  }
  ,
  {
    "id":"126725",
    "name":"Store"
  }
  ,
  {
    "id":"20386",
    "name":"marketing.name"
  }
  ,
  {
    "id":"747",
    "name":"Marketing"
  }
  ,
  {
    "id":"127217",
    "name":"Store"
  }
  ,
  {
    "id":"23623",
    "name":"marketing.name"
  }
  ,
  {
    "id":"778",
    "name":"Marketing"
  }
  ,
  {
    "id":"127907",
    "name":"Store"
  }
  ,
  {
    "id":"32550",
    "name":"marketing.name"
  }
  ,
  {
    "id":"801",
    "name":"Store112"
  }
  ,
  {
    "id":"128223",
    "name":"Pos"
  }
  ,
  {
    "id":"54606",
    "name":"Store"
  }
  ,
  {
    "id":"837",
    "name":"Marketing"
  }
  ,
  {
    "id":"128757",
    "name":"Store"
  }
  ,
  {
    "id":"69617",
    "name":"marketing.name"
  }
  ,
  {
    "id":"867",
    "name":"Marketing"
  }
  ,
  {
    "id":"128927",
    "name":"Store"
  }
  ,
  {
    "id":"72291",
    "name":"Weebly"
  }
  ,
  {
    "id":"892",
    "name":"Marketing"
  }
  ,
  {
    "id":"128983",
    "name":"Store"
  }
  ,
  {
    "id":"72510",
    "name":"marketing.name"
  }
  ,
  {
    "id":"910",
    "name":"Marketing"
  }
  ,
  {
    "id":"129099",
    "name":"Store"
  }
  ,
  {
    "id":"72517",
    "name":"marketing.name"
  }
  ,
  {
    "id":"916",
    "name":"Marketing"
  }
  ,
  {
    "id":"130115",
    "name":"Store"
  }
  ,
  {
    "id":"72521",
    "name":"marketing.name"
  }
  ,
  {
    "id":"920",
    "name":"Marketing"
  }
  ,
  {
    "id":"921",
    "name":"Marketing"
  }
  ,
  {
    "id":"131324",
    "name":"qwe"
  }
  ,
  {
    "id":"72677",
    "name":"marketing.name"
  }
  ,
  {
    "id":"950",
    "name":"Store"
  }
  ,
  {
    "id":"131329",
    "name":"asdasd"
  }
  ,
  {
    "id":"72895",
    "name":"marketing.name"
  }
  ,
  {
    "id":"976",
    "name":"Store"
  }
  ,
  {
    "id":"131333",
    "name":"NewNotificationTest"
  }
  ,
  {
    "id":"73838",
    "name":"marketing.name"
  }
  ,
  {
    "id":"991",
    "name":"Marketing"
  }
  ,
  {
    "id":"131444",
    "name":"Store"
  }
  ,
  {
    "id":"77120",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1003",
    "name":"Marketing"
  }
  ,
  {
    "id":"131458",
    "name":"sdfsdf"
  }
  ,
  {
    "id":"84799",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1026",
    "name":"Marketing"
  }
  ,
  {
    "id":"131462",
    "name":"sdfsdf"
  }
  ,
  {
    "id":"86284",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1034",
    "name":"Marketing"
  }
  ,
  {
    "id":"48",
    "name":"Store"
  }
  ,
  {
    "id":"131466",
    "name":"Store"
  }
  ,
  {
    "id":"87863",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1045",
    "name":"Marketing"
  }
  ,
  {
    "id":"71",
    "name":"Store"
  }
  ,
  {
    "id":"131471",
    "name":"qwe"
  }
  ,
  {
    "id":"89723",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1064",
    "name":"Marketing"
  }
  ,
  {
    "id":"84",
    "name":"Facebook"
  }
  ,
  {
    "id":"133149",
    "name":"restoshop"
  }
  ,
  {
    "id":"89781",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1076",
    "name":"Marketing"
  }
  ,
  {
    "id":"99",
    "name":"Facebook"
  }
  ,
  {
    "id":"134388",
    "name":"sdfdsfsdf"
  }
  ,
  {
    "id":"89787",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1108",
    "name":"Weebly"
  }
  ,
  {
    "id":"117",
    "name":"Facebook"
  }
  ,
  {
    "id":"135411",
    "name":"12"
  }
  ,
  {
    "id":"89813",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1137",
    "name":"Marketing"
  }
  ,
  {
    "id":"121",
    "name":"Facebook"
  }
  ,
  {
    "id":"135422",
    "name":"asdasd"
  }
  ,
  {
    "id":"89835",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1144",
    "name":"Marketing"
  }
  ,
  {
    "id":"135",
    "name":"Facebook"
  }
  ,
  {
    "id":"135658",
    "name":"ff"
  }
  ,
  {
    "id":"89842",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1155",
    "name":"Marketing"
  }
  ,
  {
    "id":"152",
    "name":"Facebook"
  }
  ,
  {
    "id":"135665",
    "name":"sdf"
  }
  ,
  {
    "id":"89856",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1165",
    "name":"Marketing"
  }
  ,
  {
    "id":"158",
    "name":"Facebook"
  }
  ,
  {
    "id":"138264",
    "name":"sdfsdf"
  }
  ,
  {
    "id":"89906",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1172",
    "name":"Marketing"
  }
  ,
  {
    "id":"164",
    "name":"Weebly"
  }
  ,
  {
    "id":"138842",
    "name":"1"
  }
  ,
  {
    "id":"90036",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1181",
    "name":"Marketing"
  }
  ,
  {
    "id":"179",
    "name":"Facebook"
  }
  ,
  {
    "id":"141906",
    "name":"new test store"
  }
  ,
  {
    "id":"92515",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1185",
    "name":"Marketing"
  }
  ,
  {
    "id":"186",
    "name":"AAA Facebook RK"
  }
  ,
  {
    "id":"141963",
    "name":"sergio"
  }
  ,
  {
    "id":"92526",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1198",
    "name":"Marketing"
  }
  ,
  {
    "id":"202",
    "name":"Facebook"
  }
  ,
  {
    "id":"144207",
    "name":"asd"
  }
  ,
  {
    "id":"92720",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1215",
    "name":"Marketing"
  }
  ,
  {
    "id":"208",
    "name":"Facebook"
  }
  ,
  {
    "id":"144960",
    "name":"ggg"
  }
  ,
  {
    "id":"93038",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1233",
    "name":"Marketing"
  }
  ,
  {
    "id":"223",
    "name":"Store"
  }
  ,
  {
    "id":"145517",
    "name":"sdfsdf"
  }
  ,
  {
    "id":"93047",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1237",
    "name":"Marketing"
  }
  ,
  {
    "id":"237",
    "name":"Store"
  }
  ,
  {
    "id":"145904",
    "name":"sdfsdf"
  }
  ,
  {
    "id":"93378",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1250",
    "name":"Marketing"
  }
  ,
  {
    "id":"247",
    "name":"Marketing"
  }
  ,
  {
    "id":"146417",
    "name":"aasd"
  }
  ,
  {
    "id":"94969",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1258",
    "name":"Marketing"
  }
  ,
  {
    "id":"269",
    "name":"Marketing"
  }
  ,
  {
    "id":"148307",
    "name":"marketing.name"
  }
  ,
  {
    "id":"96871",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1262",
    "name":"Marketing"
  }
  ,
  {
    "id":"284",
    "name":"Marketing"
  }
  ,
  {
    "id":"148481",
    "name":"marketing.name"
  }
  ,
  {
    "id":"98681",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1270",
    "name":"Marketing"
  }
  ,
  {
    "id":"288",
    "name":"Marketing"
  }
  ,
  {
    "id":"150163",
    "name":"rdgdfgdg"
  }
  ,
  {
    "id":"99505",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1305",
    "name":"Marketing"
  }
  ,
  {
    "id":"315",
    "name":"Marketing"
  }
  ,
  {
    "id":"151788",
    "name":"123"
  }
  ,
  {
    "id":"100208",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1309",
    "name":"Marketing"
  }
  ,
  {
    "id":"323",
    "name":"Marketing"
  }
  ,
  {
    "id":"159284",
    "name":"Pos"
  }
  ,
  {
    "id":"100280",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1324",
    "name":"Store"
  }
  ,
  {
    "id":"327",
    "name":"Marketing"
  }
  ,
  {
    "id":"161026",
    "name":"marketing.name"
  }
  ,
  {
    "id":"101134",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1341",
    "name":"Marketing"
  }
  ,
  {
    "id":"354",
    "name":"Marketing"
  }
  ,
  {
    "id":"161359",
    "name":"marketing.name"
  }
  ,
  {
    "id":"103618",
    "name":"marketing.name"
  }
  ,
  {
    "id":"1376",
    "name":"Marketing"
  }
  ,
  {
    "id":"366",
    "name":"Marketing"
  }
  ,
  {
    "id":"162101",
    "name":"Pos"
  }
  ,
  {
    "id":"105136",
    "name":"Store"
  }
  ,
  {
    "id":"1390",
    "name":"Marketing"
  }
  ,
  {
    "id":"402",
    "name":"Marketing"
  }
  ,
  {
    "id":"162840",
    "name":"Pos"
  }
  ,
  {
    "id":"108576",
    "name":"Pos"
  }
  ,
  {
    "id":"1518",
    "name":"Marketing"
  }
  ,
  {
    "id":"406",
    "name":"Marketing"
  }
  ,
  {
    "id":"163457",
    "name":"Pos"
  }
  ,
  {
    "id":"108599",
    "name":"Pos"
  }
  ,
  {
    "id":"1817",
    "name":"Marketing"
  }
  ,
  {
    "id":"413",
    "name":"Marketing"
  }
  ,
  {
    "id":"164448",
    "name":"Pos"
  }
  ,
  {
    "id":"108626",
    "name":"Pos"
  }
  ,
  {
    "id":"1926",
    "name":"Facebook"
  }
  ,
  {
    "id":"423",
    "name":"Marketing"
  }
  ,
  {
    "id":"167906",
    "name":"sdf"
  }
  ,
  {
    "id":"108721",
    "name":"Pos"
  }
  ,
  {
    "id":"2013",
    "name":"Test"
  }
  ,
  {
    "id":"452",
    "name":"Marketing"
  }
  ,
  {
    "id":"169573",
    "name":"qw"
  }
  ,
  {
    "id":"110454",
    "name":"marketing.name"
  }
  ,
  {
    "id":"2090",
    "name":"Store"
  }
  ,
  {
    "id":"475",
    "name":"Marketing"
  }
  ,
  {
    "id":"169729",
    "name":"zxa1"
  }
  ,
  {
    "id":"113374",
    "name":"marketing.name"
  }
  ,
  {
    "id":"2572",
    "name":"12121"
  }
  ,
  {
    "id":"485",
    "name":"Marketing"
  }
  ,
  {
    "id":"172227",
    "name":"marketing.name"
  }
  ,
  {
    "id":"122117",
    "name":"Store"
  }
  ,
  {
    "id":"3008",
    "name":"Apple Watch"
  }
  ,
  {
    "id":"493",
    "name":"Marketing"
  }
  ,
  {
    "id":"172382",
    "name":"Alexey store"
  }
  ,
  {
    "id":"123802",
    "name":"Store"
  }
  ,
  {
    "id":"5705",
    "name":"marketing.name"
  }
  ,
  {
    "id":"504",
    "name":"Marketing"
  }
  ,
  {
    "id":"174273",
    "name":"Pos"
  }
  ,
  {
    "id":"125477",
    "name":"Store"
  }
  ,
  {
    "id":"7541",
    "name":"marketing.name"
  }
  ,
  {
    "id":"559",
    "name":"Marketing"
  }
  ,
  {
    "id":"125815",
    "name":"Pos"
  }
  ,
  {
    "id":"8454",
    "name":"marketing.name"
  }
  ,
  {
    "id":"732",
    "name":"Marketing"
  }
  ,
  {
    "id":"126482",
    "name":"marketing.name"
  }
  ,
  {
    "id":"18113",
    "name":"marketing.name"
  }
  ,
  {
    "id":"742",
    "name":"Marketing"
  }
  ,
  {
    "id":"126726",
    "name":"Store"
  }
  ,
  {
    "id":"20471",
    "name":"marketing.name"
  }
  ,
  {
    "id":"749",
    "name":"Marketing"
  }
  ,
  {
    "id":"127342",
    "name":"Store"
  }
  ,
  {
    "id":"26768",
    "name":"marketing.name"
  }
  ,
  {
    "id":"779",
    "name":"Marketing"
  }
  ,
  {
    "id":"127965",
    "name":"Store"
  }
  ,
  {
    "id":"36203",
    "name":"marketing.name"
  }
  ,
  {
    "id":"806",
    "name":"Marketing"
  }
  ,
  {
    "id":"128380",
    "name":"Store"
  }
  ,
  {
    "id":"55762",
    "name":"marketing.name"
  }
  ,
  {
    "id":"846",
    "name":"Marketing"
  }
  ,
  {
    "id":"128758",
    "name":"Store"
  }
  ,
  {
    "id":"69640",
    "name":"marketing.name"
  }
  ,
  {
    "id":"868",
    "name":"Marketing"
  }
  ,
  {
    "id":"128928",
    "name":"Store"
  }
  ,
  {
    "id":"72506",
    "name":"marketing.name"
  }
  ,
  {
    "id":"902",
    "name":"Marketing"
  }
  ,
  {
    "id":"129091",
    "name":"Store"
  }
  ,
  {
    "id":"72511",
    "name":"marketing.name"
  }
  ,
  {
    "id":"912",
    "name":"Marketing"
  }
  ,
  {
    "id":"129103",
    "name":"Store"
  }
  ,
  {
    "id":"72518",
    "name":"marketing.name"
  }
  ,
  {
    "id":"917",
    "name":"Marketing"
  }
  ,
  {
    "id":"130437",
    "name":"Store"
  }
  ,
  {
    "id":"72522",
    "name":"marketing.name"
  }
],
  "shipping_methods":["flat_rate", "total_order"],
  "specific_statuses":[
    {
      key:'ACCEPTED',
      name:'transactions_specific_statuses.ACCEPTED',
      payment_method:[
        'santander_invoice_de'
      ]
    },
    {
      key:'STATUS_SANTANDER_APPROVED_WITH_REQUIREMENTS',
      name:'transactions_specific_statuses.STATUS_SANTANDER_APPROVED_WITH_REQUIREMENTS',
      payment_method:[
        'santander_pos_installment',
        'santander_installment'
      ]
    },
    {
      key:'STATUS_SANTANDER_AUTOMATIC_DECLINE',
      name:'transactions_specific_statuses.STATUS_SANTANDER_AUTOMATIC_DECLINE',
      payment_method:[
        'santander_pos_installment',
        'santander_installment',
        'santander_ccp_installment'
      ]
    },
    {
      key:'STATUS_SANTANDER_IN_DECISION',
      name:'transactions_specific_statuses.STATUS_SANTANDER_IN_DECISION',
      payment_method:[
        'santander_pos_installment',
        'santander_installment',
        'santander_ccp_installment'
      ]
    },
    {
      key:'STATUS_SANTANDER_APPROVED',
      name:'transactions_specific_statuses.STATUS_SANTANDER_APPROVED',
      payment_method:[
        'santander_installment',
        'santander_pos_installment',
        'santander_ccp_installment'
      ]
    },
    {
      key:'STATUS_SANTANDER_DEFERRED',
      name:'transactions_specific_statuses.STATUS_SANTANDER_DEFERRED',
      payment_method:[
        'santander_pos_installment'
      ]
    },
    {
      key:'STATUS_SANTANDER_CANCELLED',
      name:'transactions_specific_statuses.STATUS_SANTANDER_CANCELLED',
      payment_method:[
        'santander_installment',
        'santander_pos_installment',
        'santander_ccp_installment'
      ]
    },
    {
      key:'DENIED',
      name:'transactions_specific_statuses.DENIED',
      payment_method:[
        'santander_invoice_de'
      ]
    },
    {
      key:'STATUS_SANTANDER_IN_PROCESS',
      name:'transactions_specific_statuses.STATUS_SANTANDER_IN_PROCESS',
      payment_method:[
        'santander_installment',
        'santander_ccp_installment'
      ]
    },
    {
      key:'NEED_MORE_INFO_SIFO',
      name:'transactions_specific_statuses.NEED_MORE_INFO_SIFO',
      payment_method:[
        'santander_installment_no'
      ]
    },
    {
      key:'NEW_TRANSACTION',
      name:'transactions_specific_statuses.NEW_TRANSACTION',
      payment_method:[
        'santander_factoring_de'
      ]
    },
    {
      key:'REJECTED_VALIDATION',
      name:'transactions_specific_statuses.REJECTED_VALIDATION',
      payment_method:[
        'santander_factoring_de'
      ]
    },
    {
      key:'SUCCESS',
      name:'transactions_specific_statuses.SUCCESS',
      payment_method:[
        'santander_factoring_de'
      ]
    },
    {
      key:'untraceable',
      name:'transactions_specific_statuses.untraceable',
      payment_method:[
        'sofort'
      ]
    },
    {
      key:'PENDING',
      name:'transactions_specific_statuses.PENDING',
      payment_method:[
        'santander_invoice_de',
        'santander_installment_se',
        'santander_installment_dk'
      ]
    },
    {
      key:'REJECTED',
      name:'transactions_specific_statuses.REJECTED',
      payment_method:[
        'santander_installment_no',
        'santander_invoice_no',
        'santander_installment_dk',
        'santander_installment_se',
        'santander_pos_installment_se'
      ]
    },
    {
      key:'SALE',
      name:'transactions_specific_statuses.SALE',
      payment_method:[
        'payex_creditcard',
        'payex_faktura'
      ]
    },
    {
      key:'APPROVED',
      name:'transactions_specific_statuses.APPROVED',
      payment_method:[
        'santander_installment_se',
        'santander_invoice_no',
        'santander_installment_no',
        'santander_installment_dk',
        'santander_pos_installment_se',
        'santander_installment'
      ]
    },
    {
      key:'STATUS_SANTANDER_SHOP_TEMPORARY_APPROVED',
      name:'transactions_specific_statuses.STATUS_SANTANDER_SHOP_TEMPORARY_APPROVED',
      payment_method:[
        'santander_installment',
        'santander_ccp_installment',
        'santander_pos_installment'
      ]
    },
    {
      key:'AUTHORIZE',
      name:'transactions_specific_statuses.AUTHORIZE',
      payment_method:[
        'payex_faktura',
        'payex_creditcard'
      ]
    },
    {
      key:'CANCEL',
      name:'transactions_specific_statuses.CANCEL',
      payment_method:[
        'payex_faktura',
        'payex_creditcard'
      ]
    },
    {
      key:'SIGNED',
      name:'transactions_specific_statuses.SIGNED',
      payment_method:[
        'santander_installment_no',
        'santander_installment_se',
        'santander_invoice_no',
        'santander_pos_installment_se',
        'santander_installment_dk'
      ]
    },
    {
      key:'APPLICATION_NOT_CREATED',
      name:'transactions_specific_statuses.APPLICATION_NOT_CREATED',
      payment_method:[
        'santander_installment_no'
      ]
    },
    {
      key:'STATUS_SANTANDER_DECLINED',
      name:'transactions_specific_statuses.STATUS_SANTANDER_DECLINED',
      payment_method:[
        'santander_installment',
        'santander_pos_installment'
      ]
    },
    {
      key:'CANCELLED',
      name:'transactions_specific_statuses.CANCELLED',
      payment_method:[
        'santander_invoice_no',
        'santander_installment_dk',
        'santander_installment_no',
        'santander_installment_se',
        'santander_invoice_de',
        'santander_pos_installment_se'
      ]
    },
    {
      key:'REJECTED_RISK',
      name:'transactions_specific_statuses.REJECTED_RISK',
      payment_method:[
        'santander_factoring_de'
      ]
    },
    {
      key:'CREDIT',
      name:'transactions_specific_statuses.CREDIT',
      payment_method:[
        'payex_faktura'
      ]
    },
    {
      key:'PROCESSING',
      name:'transactions_specific_statuses.PROCESSING',
      payment_method:[
        'santander_invoice_no',
        'santander_installment_no'
      ]
    },
    {
      key:'NEED_MORE_INFO_STUDENT_IIR',
      name:'transactions_specific_statuses.NEED_MORE_INFO_STUDENT_IIR',
      payment_method:[
        'santander_installment_no'
      ]
    }
  ].filter((value, index, self) => self.findIndex((item) => item.key === value.key) === index)
};

export const businessVatsMock: any[] = [
  {
    "id":"100",
    "country":"DE",
    "value":"19.00",
    "uuid":"b496773b-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"101",
    "country":"DE",
    "value":"7.00",
    "uuid":"b496797d-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"102",
    "country":"DE",
    "value":"0.00",
    "uuid":"b49679d6-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"103",
    "country":"GB",
    "value":"20.00",
    "uuid":"b4967a0b-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"104",
    "country":"GB",
    "value":"5.00",
    "uuid":"b4967a3c-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"105",
    "country":"GB",
    "value":"0.00",
    "uuid":"b4967a6d-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"106",
    "country":"ES",
    "value":"21.00",
    "uuid":"b4967a9c-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"107",
    "country":"ES",
    "value":"10.00",
    "uuid":"b4967ac9-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"108",
    "country":"ES",
    "value":"4.00",
    "uuid":"b4967af7-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"109",
    "country":"CY",
    "value":"19.00",
    "uuid":"b4967b28-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"110",
    "country":"CY",
    "value":"9.00",
    "uuid":"b4967b56-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"111",
    "country":"CY",
    "value":"5.00",
    "uuid":"b4967b83-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"112",
    "country":"CY",
    "value":"0.00",
    "uuid":"b4967bb3-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"113",
    "country":"BE",
    "value":"21.00",
    "uuid":"b4967be0-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"114",
    "country":"BE",
    "value":"12.00",
    "uuid":"b4967c0e-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"115",
    "country":"BE",
    "value":"6.00",
    "uuid":"b4967c3e-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"116",
    "country":"BE",
    "value":"0.00",
    "uuid":"b4967c6b-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"117",
    "country":"BG",
    "value":"20.00",
    "uuid":"b4967c98-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"118",
    "country":"BG",
    "value":"9.00",
    "uuid":"b4967cc6-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"119",
    "country":"BG",
    "value":"0.00",
    "uuid":"b4967cf6-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"120",
    "country":"CZ",
    "value":"21.00",
    "uuid":"b4967d23-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"121",
    "country":"CZ",
    "value":"15.00",
    "uuid":"b4967d50-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"122",
    "country":"CZ",
    "value":"10.00",
    "uuid":"b4967d7f-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"123",
    "country":"DK",
    "value":"25.00",
    "uuid":"b4967dad-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"124",
    "country":"DK",
    "value":"0.00",
    "uuid":"b4967dd9-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"125",
    "country":"EE",
    "value":"20.00",
    "uuid":"b4967e19-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"126",
    "country":"EE",
    "value":"9.00",
    "uuid":"b4967e67-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"127",
    "country":"EE",
    "value":"0.00",
    "uuid":"b4967f1a-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"128",
    "country":"GR",
    "value":"23.00",
    "uuid":"b4967f78-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"129",
    "country":"GR",
    "value":"13.00",
    "uuid":"b4967fcf-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"130",
    "country":"GR",
    "value":"6.50",
    "uuid":"b4968024-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"131",
    "country":"GR",
    "value":"0.00",
    "uuid":"b4968076-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"132",
    "country":"FR",
    "value":"20.00",
    "uuid":"b49680ad-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"133",
    "country":"FR",
    "value":"10.00",
    "uuid":"b49680de-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"134",
    "country":"FR",
    "value":"5.50",
    "uuid":"b496810e-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"135",
    "country":"FR",
    "value":"2.10",
    "uuid":"b4968140-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"136",
    "country":"HR",
    "value":"25.00",
    "uuid":"b496816d-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"137",
    "country":"HR",
    "value":"13.00",
    "uuid":"b496819c-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"138",
    "country":"HR",
    "value":"5.00",
    "uuid":"b49681ca-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"139",
    "country":"HR",
    "value":"0.00",
    "uuid":"b49681f9-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"140",
    "country":"IE",
    "value":"23.00",
    "uuid":"b4968227-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"141",
    "country":"IE",
    "value":"13.50",
    "uuid":"b4968255-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"142",
    "country":"IE",
    "value":"9.00",
    "uuid":"b4968285-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"143",
    "country":"IE",
    "value":"4.80",
    "uuid":"b49682b4-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"144",
    "country":"IT",
    "value":"22.00",
    "uuid":"b49682e2-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"145",
    "country":"IT",
    "value":"10.00",
    "uuid":"b496830f-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"146",
    "country":"IT",
    "value":"4.00",
    "uuid":"b496833f-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"147",
    "country":"IT",
    "value":"0.00",
    "uuid":"b496836c-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"148",
    "country":"LV",
    "value":"21.00",
    "uuid":"b496839a-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"149",
    "country":"LV",
    "value":"12.00",
    "uuid":"b49683c9-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"150",
    "country":"LV",
    "value":"0.00",
    "uuid":"b49683f7-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"151",
    "country":"LT",
    "value":"21.00",
    "uuid":"b4968426-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"152",
    "country":"LT",
    "value":"9.00",
    "uuid":"b4968458-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"153",
    "country":"LT",
    "value":"5.00",
    "uuid":"b4968487-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"154",
    "country":"LT",
    "value":"0.00",
    "uuid":"b49684b8-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"155",
    "country":"LU",
    "value":"17.00",
    "uuid":"b49684e8-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"156",
    "country":"LU",
    "value":"8.00",
    "uuid":"b496851a-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"157",
    "country":"LU",
    "value":"3.00",
    "uuid":"b4968547-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"158",
    "country":"LU",
    "value":"0.00",
    "uuid":"b4968575-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"159",
    "country":"HU",
    "value":"27.00",
    "uuid":"b49685a3-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"160",
    "country":"HU",
    "value":"18.00",
    "uuid":"b49685d2-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"161",
    "country":"HU",
    "value":"5.00",
    "uuid":"b49685ff-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"162",
    "country":"HU",
    "value":"0.00",
    "uuid":"b496862f-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"163",
    "country":"MT",
    "value":"18.00",
    "uuid":"b496865c-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"164",
    "country":"MT",
    "value":"7.00",
    "uuid":"b496868a-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"165",
    "country":"MT",
    "value":"5.00",
    "uuid":"b49686b7-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"166",
    "country":"MT",
    "value":"0.00",
    "uuid":"b49686e6-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"167",
    "country":"NL",
    "value":"21.00",
    "uuid":"b4968713-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"168",
    "country":"NL",
    "value":"6.00",
    "uuid":"b4968740-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"169",
    "country":"NL",
    "value":"0.00",
    "uuid":"b496876f-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"170",
    "country":"AT",
    "value":"20.00",
    "uuid":"b496879d-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"171",
    "country":"AT",
    "value":"10.00",
    "uuid":"b49687ca-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"172",
    "country":"AT",
    "value":"0.00",
    "uuid":"b49687fa-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"173",
    "country":"PL",
    "value":"23.00",
    "uuid":"b4968826-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"174",
    "country":"PL",
    "value":"8.00",
    "uuid":"b4968854-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"175",
    "country":"PL",
    "value":"5.00",
    "uuid":"b4968881-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"176",
    "country":"PL",
    "value":"0.00",
    "uuid":"b49688b1-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"177",
    "country":"PT",
    "value":"23.00",
    "uuid":"b49688de-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"178",
    "country":"PT",
    "value":"13.00",
    "uuid":"b496890b-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"179",
    "country":"PT",
    "value":"6.00",
    "uuid":"b496893d-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"180",
    "country":"PT",
    "value":"0.00",
    "uuid":"b496896d-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"181",
    "country":"RO",
    "value":"24.00",
    "uuid":"b496899c-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"182",
    "country":"RO",
    "value":"9.00",
    "uuid":"b49689ce-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"183",
    "country":"RO",
    "value":"5.00",
    "uuid":"b49689fc-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"184",
    "country":"RO",
    "value":"0.00",
    "uuid":"b4968a2a-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"185",
    "country":"SI",
    "value":"22.00",
    "uuid":"b4968a8f-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"186",
    "country":"SI",
    "value":"9.50",
    "uuid":"b4968ac2-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"187",
    "country":"SI",
    "value":"0.00",
    "uuid":"b4968af0-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"188",
    "country":"SK",
    "value":"20.00",
    "uuid":"b4968b1d-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"189",
    "country":"SK",
    "value":"10.00",
    "uuid":"b4968b4d-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"190",
    "country":"SK",
    "value":"0.00",
    "uuid":"b4968b7a-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"191",
    "country":"FI",
    "value":"24.00",
    "uuid":"b4968ba8-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"192",
    "country":"FI",
    "value":"14.00",
    "uuid":"b4968c29-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"193",
    "country":"FI",
    "value":"10.00",
    "uuid":"b4968c57-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"194",
    "country":"FI",
    "value":"0.00",
    "uuid":"b4968c85-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"195",
    "country":"SE",
    "value":"25.00",
    "uuid":"b4968cb2-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"196",
    "country":"SE",
    "value":"12.00",
    "uuid":"b4968ce2-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"197",
    "country":"SE",
    "value":"6.00",
    "uuid":"b4968d10-6309-11e7-a2a8-5254008319f0"
  },
  {
    "id":"198",
    "country":"SE",
    "value":"0.00",
    "uuid":"b4968d3c-6309-11e7-a2a8-5254008319f0"
  },

  {
    "country":"NO",
    "value":"25.00",
  },
  {
    "country":"NO",
    "value":"15.00",
  },
  {
    "country":"NO",
    "value":"12.00",
  },
  {
    "country":"NO",
    "value":"11.11"
  }
];
