import { cloneDeep } from '@pe/checkout/utils';

import { FlowRequestDto } from '../models';

export const flowRequestFixture: () => FlowRequestDto = () => cloneDeep<FlowRequestDto>({
  channelSetId: 'c6939209-3252-4696-a394-4fee90d3038a',
  channelSource: 'Web',
  connectionId: 'abcdef123456',
  apiCallId: '9876543210',
  orderId: 'ORD123456',
  amount: 100.50,
  downPayment: 50.25,
  currency: 'EUR',
  reference: '614a1c25ec075455583500',
  cart: [
    {
      description: 'Item description',
      identifier: 'item-1',
      price: 25.25,
      quantity: 2,
      thumbnail: 'https://payever.org/item-thumbnail-1.jpg',
      name: 'Item 1',
      unit: 'pcs',
      amount: 50.50,
    },
    {
      description: 'Item description',
      identifier: 'item-2',
      price: 15.75,
      quantity: 3,
      thumbnail: 'https://payever.org/item-thumbnail-2.jpg',
      name: 'Item 2',
      unit: 'pcs',
      amount: 47.25,
    },
  ],
  billingAddress: {
    addressLine2: '123 Main St, 52322, Köln, DE',
    city: 'Köln',
    country: 'DE',
    countryName: 'Deutschland',
    email: 'test@payever.org',
    firstName: 'TestName',
    lastName: 'TestSurname',
    phone: '+1234567890',
    salutation: 'Mr.',
    street: '123 Main St',
    streetName: 'Main St',
    streetNumber: '123',
    zipCode: '52322',
    region: 'DE',
    organizationName: 'Test Inc.',
    houseExtension: 'Suite 456',
  },
  shippingAddress: {
    addressLine2: '123 Main St, 52322, Köln, DE',
    city: 'Köln',
    country: 'DE',
    countryName: 'Deutschland',
    email: 'test@payever.org',
    firstName: 'TestName',
    lastName: 'TestSurname',
    phone: '+1234567890',
    salutation: 'Mr.',
    street: '123 Main St',
    streetName: 'Main St',
    streetNumber: '123',
    zipCode: '52322',
    region: 'DE',
    organizationName: 'Test Inc.',
    houseExtension: 'Suite 456',
  },
  deliveryFee: 10.00,
  shippingMethodCode: 'DHL',
  shippingMethodName: 'DHL Shipping',
  posMerchantMode: true,
  posVerifyType: 1,
  coupon: 'DISCOUNT123',
  pluginVersion: '1.2.3',
  forceLegacyCartStep: false,
  forceLegacyUseInventory: true,
  extra: { additionalInfo: 'Some additional info' },
  noticeUrl: 'https://payever.org/notice-url',
  cancelUrl: 'https://payever.org/cancel-url',
  customerRedirectUrl: { redirectUrl: 'https://payever.org/redirect-url' },
  failureUrl: 'https://payever.org/failure-url',
  pendingUrl: 'https://payever.org/pending-url',
  successUrl: 'https://payever.org/success-url',
});
