namespace: default
priorityClass: app-10stars

replicas:
  http: 1

image:
  nginx: registry.devpayever.com/frontend/cart
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 80
  monitoringPort: 8080

resources:
  requests:
    cpu: 10m
    memory: 132Mi
  limits:
    memory: 256Mi
hpa:
  cpu:
    tarUti: 75
  mem:
    tarUti: 85
