namespace: default
priorityClass: app-10stars

replicas:
  http: 1
  consumer: 1

image:
  dist: registry.devpayever.com/frontend/builder-client
  nginx: registry.devpayever.com/frontend/builder-client
  nodejs: registry.devpayever.com/frontend/builder-client
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 80
  monitoringPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi
