export const STUDY_PROFESSIONS = ['STUDENT', 'SCHUELER'];

export const UNEMPLOYED_PROFESSIONS = [
  'ARBEITSLOSER', 'HAUSFRAU_HAUSMANN', 'PENSIONAER',
  'RENTNER', 'SCHUELER', 'STUDENT', 'BUNDESFREIWILLIGENDIENST',
];
